In [3]:
%pip install pdfplumber

Requirement already satisfied: pdfplumber in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pdfplumber) (5.13.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [4]:
import pdfplumber

In [5]:
import pandas

ModuleNotFoundError: No module named 'pandas'

In [6]:
%pip install requests pandas

Requirement already satisfied: requests in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.34.2)
Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/10.0 MB 2.3 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/10.0 MB 2.5 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/10.0 MB 4.0 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/10.0 MB 3.7 MB/s eta 0:00:02
   ----------------- ---------------------- 4.5/10.0 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/10.0 MB 3.6 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/10.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/10.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.4/10.0 MB 4.3 MB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 3.8 MB/s  0:00:03
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import requests
import pdfplumber
import pandas as pd

In [1]:
print("All libraries installed successfully!")

All libraries installed successfully!

In [3]:
import requests
print("requests: OK")

import pdfplumber
print("pdfplumber: OK")

import pandas as pd
print("pandas: OK")

requests: OK
pdfplumber: OK
pandas: OK

In [10]:
url = "https://www.chisambacouncil.gov.zm/wp-content/uploads/2025/12/2024-CDF-APPROVED-COMMUNITY-PROJECTS-CHISAMBA-1-2.pdf"
response = requests.get(url, verify=False)
print(response.status_code)
print(len(response.content))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
414535

In [12]:
with open( "Chisamba2024.pdf","wb") as f:
    f.write(response.content)
print("PDF saved Successfully")

PDF saved Successfully

In [13]:
with pdfplumber.open("chisamba2024.pdf") as pdf:
    for page in pdf.pages:
        tables = page.extract_tables()
        print(tables)

[[['SN', 'PROJECT NAME', 'PROJECT DESCRIPTION', 'WARD', 'ZONE', 'SECTOR OF\nPROJECT'], ['1', 'PROCUREMENT OF AMBULANCE FOR CHISAMBA\nCONSTITUENCY', 'PROCUREMENT OF AMBULANCE FOR\nCHISAMBA CONSTITUENCY', 'ALL', 'ALL', 'HEALTH'], ['2', "MOTOR BIKE FOR THE CHIEF'S RETAINER FOR HRH\nCHIEF CHAMUKA", "MOTOR BIKE FOR THE CHIEF'S\nRETAINER FOR HRH CHIEF CHAMUKA", 'CHAMUKA', 'CHAMUKA', 'TRANSPORT'], ['3', 'CONSTRUCTION OF MATERNITY ANNEX AT\nLOMBWA HEALTH POST', 'CONSTRUCTION OF MATERNITY ANNEX\nAT LOMBWA HEALTH POST', 'MULUNGUSHI', 'LOMBWA', 'HEALTH'], ['4', 'CONSTRUCTION OF MATERNITY ANNEX AT\nKABANGA HEALTH POST', 'CONSTRUCTION OF MATERNITY ANNEX\nAT KABANGA HEALTH POST', 'CHIKONKOMENE', 'KABANGA', 'HEALTH'], ['5', 'CONSTRUCTION OF MATERNITY ANNEX AT MISWA\nHEALTH POST', 'CONSTRUCTION OF MATERNITY ANNEX\nAT MISWA HEALTH POST', 'MISWA', '', 'HEALTH'], ['6', 'CONSTRUCTION OF MATERNITY ANNEX AT\nMUPELEKESE HEALTH POST', 'CONSTRUCTION OF MATERNITY ANNEX\nAT MUPELEKESE HEALTH POST', 'MWAPULA', 'MUPELEKESE', 'HEALTH'], ['7', 'CONSTRUCTION OF MATERNITY ANNEX AT\nLUKOSHI HEALTH POST', 'CONSTRUCTION OF MATERNITY ANNEX\nAT LUKOSHI HEALTH POST', 'MUTENGA', 'LUKOSHI', 'HEALTH'], ['8', 'CONSTRUCTION OF MATERNITY ANNEX AT\nKAMANO HEALTH POST', 'CONSTRUCTION OF MATERNITY ANNEX\nAT KAMANO HEALTH POST', 'KAMANO', 'KAMANO', 'HEALTH'], ['9', "CONSTRUCTION OF MATERNITY ANNEX AT\nMONANG'OMBE", "CONSTRUCTION OF MATERNITY ANNEX\nAT MONANG'OMBE", 'MONAGOMBE', 'MONAGOMBE', 'HEALTH'], ['10', 'CONSTRUCTION OF STAFF HOUSE AT MUSWISHI\nHEALTH POST', 'CONSTRUCTION OF STAFF HOUSE AT\nMUSWISHI HEALTH POST', 'MUSWISHI', 'MUSWISHI', 'HEALTH'], ['11', 'CONSTRUCTION OF ABLUTION BLOCK AT\nMUSWISHI HEALTH POST', 'CONSTRUCTION OF ABLUTION BLOCK\nAT MUSWISHI HEALTH POST', 'MUSWISHI', 'MUSWISHI', 'HEALTH'], ['12', 'PROCUREMENT OF A TIPPER TRUCK', 'PROCUREMENT OF A TIPPER TRUCK', 'ALL', 'ALL', 'ROAD\nDEVELOPMENT'], ['13', 'PROCUREMENT OF CULVERTS, FUELS, OILS,\nMAINTENANCE OF EQUIPMENT FOR ROAD WORKS', 'PROCUREMENT OF CULVERTS, FUELS,\nOILS, MAINTENANCE OF EQUIPMENT\nFOR ROAD WORKS', 'ALL', 'ALL', 'ROAD\nDEVELOPMENT']]]
[[['SN', 'PROJECT NAME', 'PROJECT DESCRIPTION', 'WARD', 'ZONE', 'SECTOR OF\nPROJECT'], ['1', "TOP UP ON REHABILITATION OF TEACHERS' STAFF\nHOUSES AT KAPUTI PRIMARY SCHOOL", "TOP UP ON REHABILITATION OF\nTEACHERS' STAFF HOUSES AT KAPUTI\nPRIMARY SCHOOL", 'CHAMUKA', 'KAPUTI', 'EDUCATION'], ['2', 'REHABILITATION OF 1X3 CLASSROOM BLOCK AT\nMOMBOSHI SCHOOL', 'REHABILITATION OF 1X3 CLASSROOM\nBLOCK AT MOMBOSHI SCHOOL', 'MUTENGA', 'MOMBOSHI', 'EDUCATION'], ['3', 'REHABILITATION OF TEACHER’S STAFF HOUSE AT\nMOMBOSHI SCHOOL', 'REHABILITATION OF TEACHER’S STAFF\nHOUSE AT MOMBOSHI SCHOOL', 'MUTENGA', 'MOMBOSHI', 'EDUCATION'], ['4', 'REHABILITATION OF KASAVASA ROAD', 'REHABILITATION OF KASAVASA ROAD', 'MISWA/MUTENGA', 'MISWA/MUTENGA', 'INFRASTRUCTURE'], ['5', 'CONSTRUCTION OF VIP TOILET', 'CONSTRUCTION OF VIP TOILET AT\nBOMBWE PRIMARY SCHOOL', 'MULUNGUSHI', 'BOMBWE', 'EDUCATION']]]

In [15]:
import pandas as pd
all_rows = []
with pdfplumber.open("Chisamba2024.pdf") as pdf:
    for page in pdf.pages:
        table = page.extract_table()
        all_rows.extend(table)
df = pd.DataFrame(all_rows[1:], columns=all_rows[0])
df

,SN,PROJECT NAME,PROJECT DESCRIPTION,WARD,ZONE,SECTOR OF\nPROJECT
0,1,PROCUREMENT OF AMBULANCE FOR CHISAMBA\nCONSTIT...,PROCUREMENT OF AMBULANCE FOR\nCHISAMBA CONSTIT...,ALL,ALL,HEALTH
1,2,MOTOR BIKE FOR THE CHIEF'S RETAINER FOR HRH\nC...,MOTOR BIKE FOR THE CHIEF'S\nRETAINER FOR HRH C...,CHAMUKA,CHAMUKA,TRANSPORT
2,3,CONSTRUCTION OF MATERNITY ANNEX AT\nLOMBWA HEA...,CONSTRUCTION OF MATERNITY ANNEX\nAT LOMBWA HEA...,MULUNGUSHI,LOMBWA,HEALTH
3,4,CONSTRUCTION OF MATERNITY ANNEX AT\nKABANGA HE...,CONSTRUCTION OF MATERNITY ANNEX\nAT KABANGA HE...,CHIKONKOMENE,KABANGA,HEALTH
4,5,CONSTRUCTION OF MATERNITY ANNEX AT MISWA\nHEAL...,CONSTRUCTION OF MATERNITY ANNEX\nAT MISWA HEAL...,MISWA,,HEALTH
5,6,CONSTRUCTION OF MATERNITY ANNEX AT\nMUPELEKESE...,CONSTRUCTION OF MATERNITY ANNEX\nAT MUPELEKESE...,MWAPULA,MUPELEKESE,HEALTH
6,7,CONSTRUCTION OF MATERNITY ANNEX AT\nLUKOSHI HE...,CONSTRUCTION OF MATERNITY ANNEX\nAT LUKOSHI HE...,MUTENGA,LUKOSHI,HEALTH
7,8,CONSTRUCTION OF MATERNITY ANNEX AT\nKAMANO HEA...,CONSTRUCTION OF MATERNITY ANNEX\nAT KAMANO HEA...,KAMANO,KAMANO,HEALTH
8,9,CONSTRUCTION OF MATERNITY ANNEX AT\nMONANG'OMBE,CONSTRUCTION OF MATERNITY ANNEX\nAT MONANG'OMBE,MONAGOMBE,MONAGOMBE,HEALTH
9,10,CONSTRUCTION OF STAFF HOUSE AT MUSWISHI\nHEALT...,CONSTRUCTION OF STAFF HOUSE AT\nMUSWISHI HEALT...,MUSWISHI,MUSWISHI,HEALTH
10,11,CONSTRUCTION OF ABLUTION BLOCK AT\nMUSWISHI HE...,CONSTRUCTION OF ABLUTION BLOCK\nAT MUSWISHI HE...,MUSWISHI,MUSWISHI,HEALTH
11,12,PROCUREMENT OF A TIPPER TRUCK,PROCUREMENT OF A TIPPER TRUCK,ALL,ALL,ROAD\nDEVELOPMENT
12,13,"PROCUREMENT OF CULVERTS, FUELS, OILS,\nMAINTEN...","PROCUREMENT OF CULVERTS, FUELS,\nOILS, MAINTEN...",ALL,ALL,ROAD\nDEVELOPMENT
13,SN,PROJECT NAME,PROJECT DESCRIPTION,WARD,ZONE,SECTOR OF\nPROJECT
14,1,TOP UP ON REHABILITATION OF TEACHERS' STAFF\nH...,TOP UP ON REHABILITATION OF\nTEACHERS' STAFF H...,CHAMUKA,KAPUTI,EDUCATION
15,2,REHABILITATION OF 1X3 CLASSROOM BLOCK AT\nMOMB...,REHABILITATION OF 1X3 CLASSROOM\nBLOCK AT MOMB...,MUTENGA,MOMBOSHI,EDUCATION
16,3,REHABILITATION OF TEACHER’S STAFF HOUSE AT\nMO...,REHABILITATION OF TEACHER’S STAFF\nHOUSE AT MO...,MUTENGA,MOMBOSHI,EDUCATION
17,4,REHABILITATION OF KASAVASA ROAD,REHABILITATION OF KASAVASA ROAD,MISWA/MUTENGA,MISWA/MUTENGA,INFRASTRUCTURE
18,5,CONSTRUCTION OF VIP TOILET,CONSTRUCTION OF VIP TOILET AT\nBOMBWE PRIMARY ...,MULUNGUSHI,BOMBWE,EDUCATION

In [16]:
df.to_csv("Chisamba2024_raw.csv" , index=False)
print("Raw dataset saved")

Raw dataset saved

In [17]:
import os

print(os.path.exists("Chisamba2024_raw.csv"))
print(os.path.getsize("Chisamba2024_raw.csv"))

True
2644

In [18]:
import requests

url = "https://www.chisambacouncil.gov.zm/?p=2290"

response = requests.get(url, verify=False)

print(response.status_code)
print(len(response.text))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
83823

In [19]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

text = soup.get_text(" ", strip=True)

print(text[:5000])

CHISAMBA TOWN COUNCIL DISBURSES k4.1 MILLION IN CDF LOANS TO BENEFICIARY GROUPS – Chisamba Town Council Chipembi Road | chisambadcouncil@gmail.com | +260 977 793 140 Home About Open menu Who we are Vision Mission Mandate Departments Services News Updates CDF ZDSP Media Center Open menu Application Forms Publications Photo Gallery FAQs Contact Us Menu Home About Open menu Who we are Vision Mission Mandate Departments Services News Updates CDF ZDSP Media Center Open menu Application Forms Publications Photo Gallery FAQs Contact Us Search CHISAMBA TOWN COUNCIL DISBURSES k4.1 MILLION IN CDF LOANS TO BENEFICIARY GROUPS Chisamba Zambia 14th November,2025. Chisamba Town Council has disbursed a total of K4,100,200 in Constituency Development Fund (CDF) loans to 24 Companies,Clubs and Cooperatives drawn from all 12 wards in the District, in an effort to enhance local economic development and empower community led-enterprises. Chisamba Constituency Member of Parliament Ms Chushi Kasanda, officiated at the handover ceremony which was held at the Civic Center. She expressed pride in the continued growth and impact of CDF in the Constituency. Hon Kasanda noted that the loans will support a wide range of business ventures,including livestock farming,fish farming,butchery operations,irrigation farming and transport services among others. She further extended gratitude to the Republican President Hakainde Hichilema for expanding the CDF allocation from 1.6 million in 2021 to 40 million in 2026,emphasizing that the increased funding has allowed more Zambians particularly women and youths to access grants and loans for sustainable development. During the same event,the CDF Chairperson Ms. Titamenji Palale,urged the loan receipients to use the funds responsibly,emphasizing that prudent use and repayment of loans,would ensure that more community members to benefit from the program. Delivering Closing remarks, Provincial Local Government Officer Mr. Clint Susiku stated that he was in the district to witness the CDF loan disbursement and to monitor the on-going voter education and mass registration exercise. He highlighted the importance of ensuring that communities remain well informed and actively participate in democratic processes. Published December 8, 2025 By Dorothy Phiri Categorized as Uncategorized Post navigation Previous post CHISAMBA RECORDS 19,219 NEW VOTERS REGISTRATIONS AND UPDATES AS ECZ COMMISIONER MUTITI VISITS TO MONITOR PROGRESS Contact Information Chisamba Town Council Chipembi Road, Chisamba District, Central Province, Zambia Tel:+260 574144495 P.O Box: 820030 Email : chisambatowncouncil@gmail.com : chisamba.council@mlgrd.gov.zm Complaints Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2023. SMART Zambia Institute. All Rights Reserved.

In [20]:
data = {
    "Date": "2025-11-14",
    "Total_Disbursed_Kwacha": 4100200,
    "Beneficiary_Groups": 24,
    "Wards_Covered": 12,
    "CDF_Subprogram": "Loans",
    "Business_Areas": "Livestock farming; Fish farming; Butchery operations; Irrigation farming; Transport services",
    "Event_Location": "Civic Center",
    "Source": "Chisamba Town Council"
}

cdf_loans_df = pd.DataFrame([data])

cdf_loans_df

,Date,Total_Disbursed_Kwacha,Beneficiary_Groups,Wards_Covered,CDF_Subprogram,Business_Areas,Event_Location,Source
0,2025-11-14,4100200,24,12,Loans,Livestock farming; Fish farming; Butchery oper...,Civic Center,Chisamba Town Council

In [21]:
cdf_loans_df.to_csv("Chisamba2025_CDF_Loan_Disbursement_raw.csv", index=False)

In [22]:
import requests

url_2023 = "https://www.chisambacouncil.gov.zm/wp-content/uploads/2025/12/2023-CDF-COMMUNITY-PROJECTS-APPROVED-1.pdf"

response = requests.get(url_2023, verify=False)

print(response.status_code)
print(len(response.content))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
296217

In [23]:
with open("Chisamba2023approved.pdf", "wb") as f:
    f.write(response.content)

print("PDF saved successfully")

PDF saved successfully

In [24]:
import pdfplumber

all_rows = []

with pdfplumber.open("Chisamba2023approved.pdf") as pdf:
    print("Pages:", len(pdf.pages))
    
    for page in pdf.pages:
        tables = page.extract_tables()
        print(tables)

Pages: 1
[[['MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT', None, None, None, None, None, None, None], ['COMMUNITY PROJECTS\nName of Local Authority: CHISAMBA TOWN COUNCIL', None, None, None, None, None, None, None], ['No.', 'Project Name', 'Project Description', 'Sector', 'Type of Project', 'Constituency', 'Ward', 'Approved Amount'], ['1', 'Purchase of 5500\ndesks foe all\nschools', 'Supply of 5500 desks for all\nschools with secure\nstructures or buildings', 'Education', 'New Purchase', 'Chisamba', 'All wards', '7,700,000.00'], ['2', 'Road\nmaintenance of\nselected priority\nroads in all wards', 'Purchase of fuels and oils\nincluding servicing of the\nroad equipment- bought\nunder 2022 CDF- for the\nmaintenance of priority\nroads in all wards', 'Roads and\nTransport', 'Maintenance', 'Chisamba', 'All wards', '4,381,997.93'], ['3', 'Rehabilitation of\nboreholes in all\nwards', 'Provision of improved water\nand sanitation systems in the\ndistrict- rehabilitation of\nbroken down boreholes in all\nwards', 'Water', 'Rehabilitation', 'Chisamba', 'All wards', '650,000.00'], ['4', 'Construction of\nChamuka Royal\nPalace', "Construction of Chamuka\nRoyal Palace under Chief\nChamuka's chiefdom", 'Traditional\naffairs', 'New Construction', 'Chisamba', 'Chamuka\nward', '1,000,000.00'], ['5', 'Dumpsite mainten', 'Establishment of the\naDnucmep isni tLei teta ward', 'Public Health', 'Maintenance', 'Chisamba', 'Liteta ward', '350,000.00'], ['6', 'Purchase of an\nambulance', 'Procurement of an\nAmbulance', 'Health', 'New Purchase', 'Chisamba', 'All wards', '1,250,000.00'], ['', '', 'TOTAL', '', '', '', '', '15,331,997.93']]]

In [25]:
rows = [
    row for row in all_rows if row[0] not in ["", "No."]
]

columns = [
    "Project ID",
    "Project Name",
    "Project Description",
    "Sector",
    "Type of Project",
    "Constituency",
    "Ward",
    "Approved Amount"
]

df_2023 = pd.DataFrame(rows, columns=columns)

df_2023

Empty DataFrame
Columns: [Project ID, Project Name, Project Description, Sector, Type of Project, Constituency, Ward, Approved Amount]
Index: []

In [26]:
df_2023.to_csv("Chisamba2023_CDF_Projects_raw.csv", index=False)

In [27]:
import requests

url_2025 = "https://www.chisambacouncil.gov.zm/wp-content/uploads/2025/06/2025-CDF-CHISAMBA-CONSTITUENCY-COMMUNITY-PROJECTS-APPROVED-LIST.pdf"

response = requests.get(url_2025, verify=False)

print(response.status_code)
print(len(response.content))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
1083982

In [28]:
with open("Chisamba2025approved.pdf", "wb") as f:
    f.write(response.content)

print("PDF saved successfully")

PDF saved successfully

In [29]:
import pdfplumber

all_rows_2025 = []

with pdfplumber.open("Chisamba2025approved.pdf") as pdf:
    print("Pages:", len(pdf.pages))
    
    for page in pdf.pages:
        tables = page.extract_tables()
        print(tables)

Pages: 2
[]
[]

In [30]:
%pip install pytesseract pdf2image

Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: packaging>=21.3 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pytesseract) (26.0)
Requirement already satisfied: Pillow>=8.0.0 in C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pytesseract) (12.3.0)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Installing collected packages: pytesseract, pdf2image

   ---------------------------------------- 0/2 [pytesseract]
   ---------------------------------------- 0/2 [pytesseract]
   ---------------------------------------- 2/2 [pdf2image]

Successfully installed pdf2image-1.17.0 pytesseract-0.3.13
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script pytesseract.exe is installed in 'C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [31]:
import pytesseract

print(pytesseract.get_tesseract_version())

TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

In [1]:
import pytesseract

print(pytesseract.get_tesseract_version())

TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

In [2]:
import os

print(os.path.exists(r"C:\Program Files\Tesseract-OCR\tesseract.exe"))

True

In [3]:
import pytesseract

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

print(pytesseract.get_tesseract_version())

5.3.0.20221214

In [4]:
from pdf2image import convert_from_path

pages = convert_from_path("Chisamba2025approved.pdf")

print("Pages converted:", len(pages))

PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

In [5]:
from pdf2image import convert_from_path

pages = convert_from_path(
    "Chisamba2025approved.pdf",
    poppler_path=r"C:\Program Files\poppler-26.07.0\Library\bin"
)

print("Pages converted:", len(pages))

Pages converted: 2

In [6]:
import pytesseract

for i, page in enumerate(pages):
    text = pytesseract.image_to_string(page)
    
    print(f"\n--- PAGE {i+1} ---")
    print(text)

--- PAGE 1 ---
2025 CDF CHISAMBA CONSTITUENCY COMMUNITY PROJECTS APPROVED LIST

SN) [PROJECT NAME PROJECT DESCRIPTION mn NaN WARDEN :
CONSTRUCTION OF 1X3 CLASSROOM CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT MUTABA COMMUNITY BLOCK AT MUTABA COMMUNITY
1|SCHOOL SCHOOL CHISAMBA MUTABA EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM: [CONSTRUCTION OF 1X3 CLASSROOM |
BLOCK AT MUCHINGA COMMUNITY BLOCK AT MUCHINGA COMMUNITY
2|SCHOOL _ {SCHOOL CHAMUKA LUANO EDUCATION
CONTRUCTION OF A 1X2 CRB AT CONTRUCTION OF A 1X2 CRB AT
3} MAKENI MAKENI KAMANO CHALAMPA EDUCATION
CONSTRUCTION OF STAFF HOUSE AT |CONSTRUCTION OF STAFF HOUSE AT
4|KAMANO MATERNITY ANNEX KAMANO MATERNITY ANNEX KAMANO KAMANO HEALTH
CONTRUCTION OF A MATERNITY CONTRUCTION OF A MATERNITY
S/ANNEX AT MWANTAYA CLINIC ANNEX AT MWANTAYA CLINIC MWANTAYA MWANTAYA HEALTH
CONSTRUCTION OF 1X3 CLASSROOM: |CONSTRUCTION OF 1X3 CLASSROOM
6|BLOCK AT NALUFWI PRIMARY SCHOOL |BLOCK AT NALUFWI PRIMARY SCHOOL |LITETA NALUFWI EDUCATION _|
DRILLING OF A BOREHOLE AT DRILLING OF A BOREHOLE AT
PUKUMA B / TUSHOMEKE PUKUMA B / TUSHOMEKE WATER AND
7|COMMUNITY COMMUNITY LITETA NALUFWI SANITATION
CONSTRUCTION OF 1X3 AT CONSTRUCTION OF 1X3 AT
8|MONANG'OMBE PRIMARY SCHOOL MONANG'OMBE PRIMARY SCHOOL MONANG'OMBE |MONANG'OMBE |EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM = |CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT KAMULOBWE PRIMARY BLOCK AT KAMULOBWE PRIMARY
9|SCHOOL SCHOOL MONANG'OMBE |KAMULOBWE EDUCATION
CONSTRUCTION OF 1X3 AT MISWA CONSTRUCTION OF 1X3 AT MISWA
10} COMMUNITY COMMUNITY | MISWA CHABUSHA _| EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM = |CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT NANSAMBILA COMMUNITY |BLOCK AT NANSAMBILA COMMUNITY
11}SCHOOL SCHOOL MULUNGUSHI BOMBWE EDUCATION
CONSTRUCTION OF A STAFF HOUSE AT|CONSTRUCTION OF A STAFF HOUSE AT}
12|/THE MATERNITY ANNEX AT LOMBWA |THE MATERNITY ANNEX AT LOMBWA_ |MULUNGUSHI LOMBWA HEALTH
CONSTRUCTION OF A STAFF HOUSE AT|CONSTRUCTION OF A STAFF HOUSE AT MULUNGUSHI
13 | MULUNGUSHI AGRO MULUNGUSHI AGRO MULUNGUSHI AGRO EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM = |CONSTRUCTION OF 1X3 CLASSROOM
14|/BLOCK AT BRUNELLI BLOCK AT BRUNELLI MUSWISHI BRUNELLI EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM: |CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT KASOSOLO SECONDARY BLOCK AT KASOSOLO SECONDARY
15|SCHOOL SCHOOL MUSWISHI KASOSOLO EDUCATION



--- PAGE 2 ---
CONSTRUCTION OF 1X3 CLASSROOM [CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT MWAPULA PRIMARY BLOCK AT MWAPULA PRIMARY
16|SCHOOL SCHOOL MWAPULA MWAPULA EDUCATION
CONSTRUCTION OF A 1x3 CONSTRUCTION OF A 1x3 |
17|CLASSROOM BLOCK AT KAPANI CLASSROOM BLOCK AT KAPANI CHIKONKOMENE |KAPANI EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM _|CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT MUFUNDA PRIMARY BLOCK AT MUFUNDA PRIMARY
18|SCHOOL SCHOOL MUTENGA MUFUNDA EDUCATION
TL
CONSTRUCTION OF 1X3 CLASSROOM [CONSTRUCTION OF 1X3 CLASSROOM
19|BLOCK AT CHISAMBA DAY BLOCK AT CHISAMBA DAY CHISAMBA CHISAMBA __|EDUCATION
~ [CONSTRUCTION OF WATER SCHEMES [CONSTRUCTION OF WATER SCHEMES |
AT KABANANA AND CHAWAMA AT KABANANA AND CHAWAMA WATER AND
20|ComPOUNDS COMPOUNDS CHISAMBA CHISAMBA SANITATION
DISASTER COMPONENT |
REHABILITATION OF A 1X4 REHABILITATION OF A 1x4
CLASSROOM BLOCK AT KASAMBA _|CLASSROOM BLOCK AT KASAMBA
1|PRIMARY SCHOOL PRIMARY SCHOOL MULUNGUSH! _|KASAMBA EDUCATION
CONSTRUCTION OF A 1x3 CONSTRUCTION OF A 1x3
CLASSROOM BLOCK ATKABANGA —_|CLASSROOM BLOCK AT KABANGA
2|PRIMARY SCHOOL PRIMARY SCHOOL CHIKONKOMENE |KABANGA EDUCATION

In [7]:
ocr_text = ""

for i, page in enumerate(pages):
    ocr_text += f"\n--- PAGE {i+1} ---\n"
    ocr_text += pytesseract.image_to_string(page)

with open("Chisamba2025Approved_OCR_raw.txt", "w", encoding="utf-8") as f:
    f.write(ocr_text)

print("Raw OCR saved successfully")

Raw OCR saved successfully

In [8]:
import pandas as pd

print(ocr_text)

--- PAGE 1 ---
2025 CDF CHISAMBA CONSTITUENCY COMMUNITY PROJECTS APPROVED LIST

SN) [PROJECT NAME PROJECT DESCRIPTION mn NaN WARDEN :
CONSTRUCTION OF 1X3 CLASSROOM CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT MUTABA COMMUNITY BLOCK AT MUTABA COMMUNITY
1|SCHOOL SCHOOL CHISAMBA MUTABA EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM: [CONSTRUCTION OF 1X3 CLASSROOM |
BLOCK AT MUCHINGA COMMUNITY BLOCK AT MUCHINGA COMMUNITY
2|SCHOOL _ {SCHOOL CHAMUKA LUANO EDUCATION
CONTRUCTION OF A 1X2 CRB AT CONTRUCTION OF A 1X2 CRB AT
3} MAKENI MAKENI KAMANO CHALAMPA EDUCATION
CONSTRUCTION OF STAFF HOUSE AT |CONSTRUCTION OF STAFF HOUSE AT
4|KAMANO MATERNITY ANNEX KAMANO MATERNITY ANNEX KAMANO KAMANO HEALTH
CONTRUCTION OF A MATERNITY CONTRUCTION OF A MATERNITY
S/ANNEX AT MWANTAYA CLINIC ANNEX AT MWANTAYA CLINIC MWANTAYA MWANTAYA HEALTH
CONSTRUCTION OF 1X3 CLASSROOM: |CONSTRUCTION OF 1X3 CLASSROOM
6|BLOCK AT NALUFWI PRIMARY SCHOOL |BLOCK AT NALUFWI PRIMARY SCHOOL |LITETA NALUFWI EDUCATION _|
DRILLING OF A BOREHOLE AT DRILLING OF A BOREHOLE AT
PUKUMA B / TUSHOMEKE PUKUMA B / TUSHOMEKE WATER AND
7|COMMUNITY COMMUNITY LITETA NALUFWI SANITATION
CONSTRUCTION OF 1X3 AT CONSTRUCTION OF 1X3 AT
8|MONANG'OMBE PRIMARY SCHOOL MONANG'OMBE PRIMARY SCHOOL MONANG'OMBE |MONANG'OMBE |EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM = |CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT KAMULOBWE PRIMARY BLOCK AT KAMULOBWE PRIMARY
9|SCHOOL SCHOOL MONANG'OMBE |KAMULOBWE EDUCATION
CONSTRUCTION OF 1X3 AT MISWA CONSTRUCTION OF 1X3 AT MISWA
10} COMMUNITY COMMUNITY | MISWA CHABUSHA _| EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM = |CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT NANSAMBILA COMMUNITY |BLOCK AT NANSAMBILA COMMUNITY
11}SCHOOL SCHOOL MULUNGUSHI BOMBWE EDUCATION
CONSTRUCTION OF A STAFF HOUSE AT|CONSTRUCTION OF A STAFF HOUSE AT}
12|/THE MATERNITY ANNEX AT LOMBWA |THE MATERNITY ANNEX AT LOMBWA_ |MULUNGUSHI LOMBWA HEALTH
CONSTRUCTION OF A STAFF HOUSE AT|CONSTRUCTION OF A STAFF HOUSE AT MULUNGUSHI
13 | MULUNGUSHI AGRO MULUNGUSHI AGRO MULUNGUSHI AGRO EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM = |CONSTRUCTION OF 1X3 CLASSROOM
14|/BLOCK AT BRUNELLI BLOCK AT BRUNELLI MUSWISHI BRUNELLI EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM: |CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT KASOSOLO SECONDARY BLOCK AT KASOSOLO SECONDARY
15|SCHOOL SCHOOL MUSWISHI KASOSOLO EDUCATION


--- PAGE 2 ---
CONSTRUCTION OF 1X3 CLASSROOM [CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT MWAPULA PRIMARY BLOCK AT MWAPULA PRIMARY
16|SCHOOL SCHOOL MWAPULA MWAPULA EDUCATION
CONSTRUCTION OF A 1x3 CONSTRUCTION OF A 1x3 |
17|CLASSROOM BLOCK AT KAPANI CLASSROOM BLOCK AT KAPANI CHIKONKOMENE |KAPANI EDUCATION
CONSTRUCTION OF 1X3 CLASSROOM _|CONSTRUCTION OF 1X3 CLASSROOM
BLOCK AT MUFUNDA PRIMARY BLOCK AT MUFUNDA PRIMARY
18|SCHOOL SCHOOL MUTENGA MUFUNDA EDUCATION
TL
CONSTRUCTION OF 1X3 CLASSROOM [CONSTRUCTION OF 1X3 CLASSROOM
19|BLOCK AT CHISAMBA DAY BLOCK AT CHISAMBA DAY CHISAMBA CHISAMBA __|EDUCATION
~ [CONSTRUCTION OF WATER SCHEMES [CONSTRUCTION OF WATER SCHEMES |
AT KABANANA AND CHAWAMA AT KABANANA AND CHAWAMA WATER AND
20|ComPOUNDS COMPOUNDS CHISAMBA CHISAMBA SANITATION
DISASTER COMPONENT |
REHABILITATION OF A 1X4 REHABILITATION OF A 1x4
CLASSROOM BLOCK AT KASAMBA _|CLASSROOM BLOCK AT KASAMBA
1|PRIMARY SCHOOL PRIMARY SCHOOL MULUNGUSH! _|KASAMBA EDUCATION
CONSTRUCTION OF A 1x3 CONSTRUCTION OF A 1x3
CLASSROOM BLOCK ATKABANGA —_|CLASSROOM BLOCK AT KABANGA
2|PRIMARY SCHOOL PRIMARY SCHOOL CHIKONKOMENE |KABANGA EDUCATION

In [9]:
import pandas as pd
raw_ocr_df = pd.DataFrame({
    "raw_ocr_text": [ocr_text]})
raw_ocr_df.to_csv("Chisamba2025approvedproject_OCR_raw.csv", index=False)
print("Raw ocr csv saved successfully.")

Raw ocr csv saved successfully.

In [10]:
import requests
url = "https://www.chisambacouncil.gov.zm/?p=2290"
response = requests.get(url, verify=False)
print("status:", response.status_code)
print("characters downloaded", len(response.text))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

status: 200
characters downloaded 84322

In [12]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")
text = soup.get_text(" ",strip=True)
print(text[:5000])

CHISAMBA TOWN COUNCIL DISBURSES k4.1 MILLION IN CDF LOANS TO BENEFICIARY GROUPS – Chisamba Town Council Chipembi Road | chisambadcouncil@gmail.com | +260 977 793 140 Home About Open menu Who we are Vision Mission Mandate Departments Services News Updates CDF ZDSP Media Center Open menu Application Forms Publications Photo Gallery FAQs Contact Us Menu Home About Open menu Who we are Vision Mission Mandate Departments Services News Updates CDF ZDSP Media Center Open menu Application Forms Publications Photo Gallery FAQs Contact Us Search CHISAMBA TOWN COUNCIL DISBURSES k4.1 MILLION IN CDF LOANS TO BENEFICIARY GROUPS Chisamba Zambia 14th November,2025. Chisamba Town Council has disbursed a total of K4,100,200 in Constituency Development Fund (CDF) loans to 24 Companies,Clubs and Cooperatives drawn from all 12 wards in the District, in an effort to enhance local economic development and empower community led-enterprises. Chisamba Constituency Member of Parliament Ms Chushi Kasanda, officiated at the handover ceremony which was held at the Civic Center. She expressed pride in the continued growth and impact of CDF in the Constituency. Hon Kasanda noted that the loans will support a wide range of business ventures,including livestock farming,fish farming,butchery operations,irrigation farming and transport services among others. She further extended gratitude to the Republican President Hakainde Hichilema for expanding the CDF allocation from 1.6 million in 2021 to 40 million in 2026,emphasizing that the increased funding has allowed more Zambians particularly women and youths to access grants and loans for sustainable development. During the same event,the CDF Chairperson Ms. Titamenji Palale,urged the loan receipients to use the funds responsibly,emphasizing that prudent use and repayment of loans,would ensure that more community members to benefit from the program. Delivering Closing remarks, Provincial Local Government Officer Mr. Clint Susiku stated that he was in the district to witness the CDF loan disbursement and to monitor the on-going voter education and mass registration exercise. He highlighted the importance of ensuring that communities remain well informed and actively participate in democratic processes. Published December 8, 2025 By Dorothy Phiri Categorized as Uncategorized Post navigation Previous post CHISAMBA RECORDS 19,219 NEW VOTERS REGISTRATIONS AND UPDATES AS ECZ COMMISIONER MUTITI VISITS TO MONITOR PROGRESS Next post PUBLIC HEALTH DEPARTMENT CONFISCATES EXPIRED GOODS DURING INSPECTIONS Contact Information Chisamba Town Council Chipembi Road, Chisamba District, Central Province, Zambia Tel:+260 574144495 P.O Box: 820030 Email : chisambatowncouncil@gmail.com : chisamba.council@mlgrd.gov.zm Complaints Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2023. SMART Zambia Institute. All Rights Reserved.

In [13]:
data = {
    "Date": "2025-11-14",
    "Total_Disbursed_Value": 4100200,
    "Currency": "ZMW",
    "Funder_Authority": "Constituency Development Fund (CDF)",
    "Total_Beneficiaries": 24,
    "Beneficiary_Type": "Companies, Clubs and Cooperatives",
    "CDF_Sub_Program": "Loans",
    "Wards_Covered": 12,
    "Business_Areas": "Livestock farming; Fish farming; Butchery operations; Irrigation farming; Transport services",
    "Event_Location": "Civic Center",
    "Source_Organization": "Chisamba Town Council"
}

In [14]:
import pandas as pd

cdf_loanskeyfield_df = pd.DataFrame([data])

print(cdf_loanskeyfield_df)

         Date  Total_Disbursed_Value Currency  \
0  2025-11-14                4100200      ZMW

                      Funder_Authority  Total_Beneficiaries  \
0  Constituency Development Fund (CDF)                   24

                    Beneficiary_Type CDF_Sub_Program  Wards_Covered  \
0  Companies, Clubs and Cooperatives           Loans             12

                                      Business_Areas Event_Location  \
0  Livestock farming; Fish farming; Butchery oper...   Civic Center

     Source_Organization
0  Chisamba Town Council

In [15]:
cdf_loanskeyfield_df.to_csv(
    "Chisamba2025_CDF_Loan_Disbursement_keyfields_raw.csv", index=False)
print("Raw CSV saved successfully.")

Raw CSV saved successfully.

In [16]:
import requests
url = "https://www.chisambacouncil.gov.zm/wp-content/uploads/2026/08/CHISAMBA-TOWN-COUNCIL-BUDGET-FOR-THE-YEAR-2026.pdf"
response = requests.get(url, verify=False)
print("status:", response.status_code)
print("file size:",len(response.content))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

status: 200
file size: 1639557

In [18]:
with open("Chisamba2026_Budget.pdf", "wb") as f:
    f.write(response.content)
print("Pdf saved")

Pdf saved

In [21]:
import pdfplumber
with pdfplumber.open("Chisamba2026_Budget.pdf") as pdf:
    page = pdf.pages[3] #page4
    tables = page.extract_tables()
print("Tables found:",len(tables))
for i, table in enumerate(tables):
    print(f"\n--- TABLE {i+1} ---")
    for row in table:
        print(row)

Tables found: 3

--- TABLE 1 ---
['CODE', 'REVENUE DESCRIPTION', 'APPROVED\nBUDGET 2026', None, 'REVISED\nBUDGET 2027', 'BUDGET\nESTIMATE 2028']
['08', 'National Support (Grants)', '', None, '', '']
['001', 'Constituency Development Fund', '40,032,550', None, '42,594,633', '45,704,041']
['002', 'Roads Grant', '6,351,370', None, '6,757,570', '7,250,873']
['003', 'Health Grant', '2,704,308', None, '2,877,384', '3,087,433']
['004', 'Local Government Equalisation Fund', '9,722,195', None, '10,445,526', '11,322,950']
['005', 'Grants in lieu of Rates', '500,000', None, '532,000', '570,836']
['099', 'Other Grants', '12,964,826', None, '13,755,202', '14,759,331']
['', 'SubItem Total', '', '72,275,249', '76,962,316', '82,695,465']
['CODE', 'REVENUE DESCRIPTION', 'APPROVED\nBUDGET 2026', None, 'REVISED\nBUDGET 2027', 'BUDGET\nESTIMATE 2028']
['09', 'Donor Support (Grants)', '', None, '', '']
['001', 'Devolution Capital Grant', '2,694,737', None, '2,867,200', '3,076,506']
['', 'SubItem Total', '', '2,694,737', '2,867,200', '3,076,506']

--- TABLE 2 ---
['Grand Total', '93,094,528', '99,113,888', '112,464,753']

--- TABLE 3 ---
['No', 'ECONOMIC CLASSIFICATION', '2024\nAPPROVED\nBUDGET (K)', '2025\nAPPROVED\nBUDGET (K)', '2026 BUDGET\nESTIMATE (K)']
['21\n22\n25\n26\n31\n32\n41', 'Personal Emoluments\nGoods and Services\nSocial Assistance Benefits\nGrants and Other Payments(Transfers)\nNon-Financial Assets\nFinancial Assets\nCurrent Liabilities (Payable within one year)', '13,868,405\n10,951,981\n(0)\n8,149,081\n18,446,866\n3,492,463\n243,116', '18,052,534\n19,073,539\n26,027,526\n8,719,516\n26,691,946\n3,736,936\n801,500', '20,254,458\n22,765,905\n10,904,013\n9,657,347\n28,106,813\n(0)\n1,405,991']
['', 'Head Total', '55,151,912', '103,103,497', '93,094,528']

In [23]:
import pandas as pd
revenue_rows = tables[0]
revenue_df = pd.DataFrame(revenue_rows)
print(revenue_df)

       0                                   1                      2  \
0   CODE                 REVENUE DESCRIPTION  APPROVED\nBUDGET 2026
1     08           National Support (Grants)
2    001       Constituency Development Fund             40,032,550
3    002                         Roads Grant              6,351,370
4    003                        Health Grant              2,704,308
5    004  Local Government Equalisation Fund              9,722,195
6    005             Grants in lieu of Rates                500,000
7    099                        Other Grants             12,964,826
8                              SubItem Total
9   CODE                 REVENUE DESCRIPTION  APPROVED\nBUDGET 2026
10    09              Donor Support (Grants)
11   001            Devolution Capital Grant              2,694,737
12                             SubItem Total

             3                     4                      5
0          NaN  REVISED\nBUDGET 2027  BUDGET\nESTIMATE 2028
1          NaN
2          NaN            42,594,633             45,704,041
3          NaN             6,757,570              7,250,873
4          NaN             2,877,384              3,087,433
5          NaN            10,445,526             11,322,950
6          NaN               532,000                570,836
7          NaN            13,755,202             14,759,331
8   72,275,249            76,962,316             82,695,465
9          NaN  REVISED\nBUDGET 2027  BUDGET\nESTIMATE 2028
10         NaN
11         NaN             2,867,200              3,076,506
12   2,694,737             2,867,200              3,076,506

In [24]:
revenue_df.to_csv(
    "chisamba2026_Budget_revenue_raw.csv", index=False)
print("Saved")

Saved

In [25]:
economic_rows = tables[2]
economic_df = pd.DataFrame(economic_rows)
print(economic_df)

                            0  \
0                          No
1  21\n22\n25\n26\n31\n32\n41
2

                                                   1  \
0                            ECONOMIC CLASSIFICATION
1  Personal Emoluments\nGoods and Services\nSocia...
2                                         Head Total

                                                   2  \
0                         2024\nAPPROVED\nBUDGET (K)
1  13,868,405\n10,951,981\n(0)\n8,149,081\n18,446...
2                                         55,151,912

                                                   3  \
0                         2025\nAPPROVED\nBUDGET (K)
1  18,052,534\n19,073,539\n26,027,526\n8,719,516\...
2                                        103,103,497

                                                   4
0                          2026 BUDGET\nESTIMATE (K)
1  20,254,458\n22,765,905\n10,904,013\n9,657,347\...
2                                         93,094,528

In [26]:
economic_df.to_csv("Budget_economic_classification_raw.csv", index=False)
print("Saved")

Saved

In [27]:
with pdfplumber.open("Chisamba2026_Budget.pdf") as pdf:
    page = pdf.pages[5]   # Page 6
    programme_tables = page.extract_tables()

print("Tables found:", len(programme_tables))

for i, table in enumerate(programme_tables):
    print(f"\n--- TABLE {i+1} ---")
    for row in table:
        print(row)

Tables found: 1

--- TABLE 1 ---
['Code', 'Programme', '2024\nApproved\nBudget(K)', '2025\nApproved\nBudget(K)', '2026\nBudget\nEstimates(K)']
['1\n2\n3\n5\n6\n7\n8\n10\n11\n12\n13\n15\n16\n17\n18', 'Constituency Development\nLocal Governance\nIntegrated Development Planning\nPublic health and Environmental Protection\nHousing and Community Amenities\nRecreation Culture and Religion\nEducation and Skills Development\nPublic Order and Safety\nManagement and Support Services\nResource Mobilisation and Management\nDistrict Health Servcies\nTransport Services\nAgricultural Services\nFisheries and Livestock\nSocial Protection and Community Development', '30,635,642', '36,058,151\n1,979,897\n5,414,058\n1,482,640\n10,312,941\n278,620\n19,241\n1,780,776\n9,826,446\n1,929,441\n2,704,308\n3,200,587\n508,842\n486,161\n27,121,390', '40,032,550\n3,504,039\n2,871,311\n1,982,973\n6,673,711\n259,999\n77,636\n1,409,572\n12,279,678\n2,261,796\n2,704,309\n6,351,370\n494,262\n503,176\n11,688,147']
[None, None, '4,647,858', None, None]
[None, None, '2,869,275', None, None]
[None, None, '807,750', None, None]
[None, None, '2,589,555', None, None]
[None, None, '10,852', None, None]
[None, None, '19,241', None, None]
[None, None, '1,105,073', None, None]
[None, None, '6,737,685', None, None]
[None, None, '1,892,527', None, None]
[None, None, '-', None, None]
[None, None, '3,742,847', None, None]
[None, None, '-', None, None]
[None, None, '93,607', None, None]
[None, None, '-', None, None]
['', 'Head Total', '55,151,912', '103,103,497', '93,094,528']

In [28]:
programme_rows = programme_tables[0]
programme_df = pd.DataFrame(programme_rows)
print(programme_df)

                                                    0  \
0                                                Code
1   1\n2\n3\n5\n6\n7\n8\n10\n11\n12\n13\n15\n16\n1...
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16

                                                    1  \
0                                           Programme
1   Constituency Development\nLocal Governance\nIn...
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                         Head Total

                            2  \
0   2024\nApproved\nBudget(K)
1                  30,635,642
2                   4,647,858
3                   2,869,275
4                     807,750
5                   2,589,555
6                      10,852
7                      19,241
8                   1,105,073
9                   6,737,685
10                  1,892,527
11                          -
12                  3,742,847
13                          -
14                     93,607
15                          -
16                 55,151,912

                                                    3  \
0                           2025\nApproved\nBudget(K)
1   36,058,151\n1,979,897\n5,414,058\n1,482,640\n1...
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                        103,103,497

                                                    4
0                          2026\nBudget\nEstimates(K)
1   40,032,550\n3,504,039\n2,871,311\n1,982,973\n6...
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                         93,094,528

In [29]:
programme_df.to_csv(
    "Programme_Budget_raw.csv", index=False)
print("saved")

saved

In [34]:
import requests
url = "https://www.chisambacouncil.gov.zm/wp-content/uploads/2024/09/CHISAMBA-DISTRICT-IDP-2024-2034.pdf"
response = requests.get(url,verify=False)
print(response.status_code)
print(len(response.content))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
8364679

In [36]:
with open("IDP_2024_2034.pdf", "wb") as f:
    f.write(response.content)
print("IDP pdf saved")

IDP pdf saved

In [37]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    print("Total pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages):
        tables = page.extract_tables()
        if tables:
            print(f"Page {i + 1}: {len(tables)} table(s)")

Total pages: 251
Page 21: 1 table(s)
Page 26: 1 table(s)
Page 27: 1 table(s)
Page 28: 1 table(s)
Page 30: 2 table(s)
Page 31: 1 table(s)
Page 32: 1 table(s)
Page 33: 2 table(s)
Page 34: 1 table(s)
Page 36: 1 table(s)
Page 37: 1 table(s)
Page 38: 1 table(s)
Page 42: 1 table(s)
Page 47: 1 table(s)
Page 48: 1 table(s)
Page 49: 1 table(s)
Page 50: 1 table(s)
Page 51: 2 table(s)
Page 52: 1 table(s)
Page 53: 1 table(s)
Page 59: 1 table(s)
Page 60: 1 table(s)
Page 61: 1 table(s)
Page 62: 1 table(s)
Page 63: 1 table(s)
Page 64: 1 table(s)
Page 65: 1 table(s)
Page 66: 2 table(s)
Page 67: 1 table(s)
Page 68: 2 table(s)
Page 69: 2 table(s)
Page 70: 1 table(s)
Page 75: 1 table(s)
Page 80: 1 table(s)
Page 81: 1 table(s)
Page 82: 1 table(s)
Page 83: 2 table(s)
Page 84: 1 table(s)
Page 85: 1 table(s)
Page 87: 1 table(s)
Page 88: 1 table(s)
Page 89: 1 table(s)
Page 90: 1 table(s)
Page 94: 1 table(s)
Page 95: 1 table(s)
Page 104: 1 table(s)
Page 105: 1 table(s)
Page 106: 1 table(s)
Page 107: 1 table(s)
Page 108: 1 table(s)
Page 109: 1 table(s)
Page 115: 1 table(s)
Page 120: 1 table(s)
Page 122: 1 table(s)
Page 124: 1 table(s)
Page 125: 1 table(s)
Page 128: 1 table(s)
Page 130: 1 table(s)
Page 131: 1 table(s)
Page 132: 1 table(s)
Page 135: 1 table(s)
Page 136: 1 table(s)
Page 137: 1 table(s)
Page 138: 1 table(s)
Page 139: 1 table(s)
Page 140: 3 table(s)
Page 141: 1 table(s)
Page 156: 1 table(s)
Page 157: 1 table(s)
Page 158: 1 table(s)
Page 159: 1 table(s)
Page 160: 1 table(s)
Page 161: 1 table(s)
Page 162: 1 table(s)
Page 163: 1 table(s)
Page 164: 1 table(s)
Page 165: 1 table(s)
Page 166: 1 table(s)
Page 167: 1 table(s)
Page 168: 1 table(s)
Page 169: 1 table(s)
Page 170: 1 table(s)
Page 171: 1 table(s)
Page 172: 1 table(s)
Page 173: 1 table(s)
Page 174: 1 table(s)
Page 175: 1 table(s)
Page 176: 1 table(s)
Page 177: 1 table(s)
Page 178: 1 table(s)
Page 179: 1 table(s)
Page 180: 2 table(s)
Page 181: 1 table(s)
Page 182: 1 table(s)
Page 183: 1 table(s)
Page 184: 1 table(s)
Page 185: 1 table(s)
Page 186: 1 table(s)
Page 187: 1 table(s)
Page 188: 2 table(s)
Page 189: 1 table(s)
Page 190: 1 table(s)
Page 191: 1 table(s)
Page 192: 3 table(s)
Page 193: 1 table(s)
Page 194: 1 table(s)
Page 195: 1 table(s)
Page 196: 1 table(s)
Page 197: 1 table(s)
Page 198: 1 table(s)
Page 199: 1 table(s)
Page 200: 1 table(s)
Page 201: 1 table(s)
Page 202: 1 table(s)
Page 203: 1 table(s)
Page 204: 1 table(s)
Page 205: 1 table(s)
Page 206: 1 table(s)
Page 207: 1 table(s)
Page 208: 1 table(s)
Page 209: 1 table(s)
Page 210: 1 table(s)
Page 211: 1 table(s)
Page 212: 1 table(s)
Page 213: 1 table(s)
Page 214: 1 table(s)
Page 215: 1 table(s)
Page 216: 1 table(s)
Page 217: 1 table(s)
Page 218: 1 table(s)
Page 219: 1 table(s)
Page 220: 1 table(s)
Page 221: 1 table(s)
Page 222: 1 table(s)
Page 223: 1 table(s)
Page 224: 1 table(s)
Page 225: 1 table(s)
Page 226: 1 table(s)
Page 227: 1 table(s)
Page 228: 1 table(s)
Page 229: 1 table(s)
Page 230: 1 table(s)
Page 231: 1 table(s)
Page 232: 1 table(s)
Page 233: 1 table(s)
Page 234: 1 table(s)
Page 235: 1 table(s)
Page 236: 1 table(s)
Page 237: 1 table(s)
Page 238: 1 table(s)
Page 239: 1 table(s)
Page 240: 1 table(s)
Page 241: 1 table(s)
Page 242: 1 table(s)
Page 243: 4 table(s)
Page 247: 1 table(s)
Page 248: 1 table(s)
Page 249: 2 table(s)

In [38]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    for page_num in range(155, 160):
        page = pdf.pages[page_num]
        tables = page.extract_tables()

        print(f"\n========== PDF PAGE {page_num + 1} ==========")

        for i, table in enumerate(tables):
            print(f"\n--- TABLE {i + 1} ---")
            for row in table:
                print(row)

========== PDF PAGE 156 ==========

--- TABLE 1 ---
['', 'ECONOMIC TRANSFORMATION AND JOB CREATION', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '']
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', 'Objective: To become an industrialised and diversified district by 2033', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '']
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', 'Strategies', '', '', 'Programmes', '', '', 'Sub Program', '', '', 'Location', '', '', 'YR 1', '', '', 'YR 2', '', '', 'YR 3', '', '', 'YR 4', '', '', 'YR 5', '', '', 'Responsible', '']
['', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', 'Improve', '', '', 'a)Infrastructure', '', '', 'Construction of 13 staff houses for', '', '', 'Chankumba and Chisamba blocks', '', '', '', '', '', '3', '', '', '3', '', '', '3', '', '', '4', '', '', 'MOA', '']
[None, 'Agricultural', None, None, 'Development', None, None, 'agricultural extension officers (2 for block', None, None, '', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, 'Production and', None, '', None, None, None, 'officers and 11 for camp officers)', None, None, 'Kanakantapa, Ploughman', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, 'Productivity', None, None, None, None, '', None, None, None, 'B,Chisamba', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, 'central,Lwamabwe,Lukoshi,Lombwa,N', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, 'alufwi,Mulungushi', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, 'Agro,Mwapula,Kasosolo and', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, 'Mwantaya', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, '', 'Rehabilitation of 12 camp houses for', '', '', 'Ploughmans', '', '', '', '', '', '3', '', '', '3', '', '', '3', '', '', '3', '', '', 'MOA', '']
[None, None, None, None, None, None, None, 'agricultural extension officers', None, None, 'B,Chowa,Bombwe,Chikokomene,Lifwa', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', None, None, None, 'mbula/3,Muswishi/4 and Chipembi', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, '', 'Construction of 7 Veterinary camp', '', '', 'All veterinary camps', '', '', '', '', '', '1', '', '', '2', '', '', '2', '', '', '2', '', '', 'MFL', '']
[None, None, None, None, None, None, None, 'houses', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', 'Rehabilitation of 5 veterinary camp', '', '', '2 Lifwambula, 2 Chipembi, 1', '', '', '', '', '', '2', '', '', '1', '', '', '1', '', '', '1', '', '', 'MFL', '']
[None, None, None, None, None, None, None, 'houses', None, None, 'Chisamba central', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', 'Construction of 2 livestock service', '', '', 'Chisamba central and Muswishi', '', '', '', '', '', '1', '', '', '', '', '', '1', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, None, None, 'centers', None, None, 'camps', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', None, None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

========== PDF PAGE 157 ==========

--- TABLE 1 ---
['', '', None, None, '', 'Construction of Animal Health', '', '', '3 Chisamba Central, 3 chisamba', '', '', '', '', '', '4', '', '', '4', '', '', '4', '', '', '4', '', '', 'MFL', '']
[None, None, None, None, None, 'Infrastructure( 16 Dip tanks)', None, None, 'west, 4 lifwambula, 3 muswishi,3', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, '', None, None, None, 'chipembi', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', '', None, None, '', 'Construction of 1 livestock breeding', '', '', 'Muswishi camp', '', '', '', '', '', '', '', '', '1', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'center', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', '', None, None, '', 'Construction of 1 Livestock market', '', '', 'Chisamba west camp-John chinena', '', '', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', 'MLF', '']
[None, None, None, None, None, 'center', None, None, 'area', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', '', None, None, '', 'Construction of 2 Slaughter facilities', '', '', 'Chisamba west camp-John chinena', '', '', '', '', '', '', '', '', '1', '', '', '', '', '', '1', '', '', 'LA/MFL', '']
[None, None, None, None, '', None, None, None, 'area and Muswishi camp', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', '', None, None, '', 'Construction of 3 storage sheds', '', '', 'Kanakantapa, Nalufwi and Bombwe', '', '', '', '', '', '', '', '', '1', '', '', '1', '', '', '1', '', '', 'MOA', '']
['', '', None, None, '', 'Construction of a fingerling production', '', '', 'New chisamba', '', '', '', '', '', '', '', '', '1', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'centre', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', '', None, None, '', 'Construction of fish feed production', '', '', 'New chisamba', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '', 'MFL', '']
[None, None, None, None, None, 'centre', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', '', 'b)Agricultural', '', '', 'Increase access to mechanisation by', '', '', 'All camps, including the 14 earmarked', '', '', '1', '', '', '1', '', '', '1', '', '', '1', '', '', '1', '', '', 'MOA,', '']
[None, None, 'mechanisation', None, None, 'farmers by linking farmers to partners', None, None, 'for creation', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, None, 'PARTNERS', None]
[None, '', None, None, None, 'such as equipment suppliers', None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '', None, None]
['', '', 'c)Enhanced', '', '', 'Provision of Farmer Input Support to', '', '', 'All camps, including the 14 earmarked', '', '', '1641', '', '', '16416', '', '', '16416', '', '', '16416', '', '', '1641', '', '', 'MOA', '']
[None, None, 'farmer support', None, None, 'farmers under the FISP to 16416', None, None, 'for creation', None, None, '6', None, '', None, None, '', None, None, '', None, None, None, '6', None, '', None, None]
['', '', 'e) Agribusiness', '', '', 'Conduct 30 sensitization meetings on', '', '', 'Nalufwi, Chowa, Chisamba central,', '', '', '6', '', '', '6', '', '', '6', '', '', '6', '', '', '6', '', '', 'MOA', '']
[None, None, 'development', None, None, 'agricultural marketing system', None, None, 'Lifwambula, Chisamba ranch and', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, '', None, None, '', None, None, None, 'Kamano', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Conduct 5 sensitization meetings to', '', '', 'All veterinary camps', '', '', '5', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'promote Animal Identification', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, 'registration-Brand Mark', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Training of 1506 Livestock farmers in', '', '', 'Muswishi, Chipembi, Lifambula,', '', '', '', '', '', '556', '', '', '500', '', '', '450', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'livestock farming as a business', None, None, 'Chisamba Central, Chisamba west', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, '', None, None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Training of 20 individual fish farmers and', '', '', 'All wards', '', '', '4', '', '', '20 ind', '', '', '', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, '4 cooperatives in fish farming as a', None, '', None, None, None, 'Coo', None, None, 'farmers', None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, 'business', None, None, None, None, None, 'perat', None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, '', None, None, None, None, None, None, 'ives', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Establishment of 3 value chains while', '', '', 'Momboshi, Chipembi, Chankumba', '', '', '', '', '', '1', '', '', '1', '', '', '1', '', '', '', '', '', 'MOA/ MFL', '']
[None, None, None, None, None, 'strengthening existing ones', None, None, 'and Muswishi camps', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', None, None, None, '', 'Establishment of one Agro processing', '', '', 'Chankumba block', '', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '', '', 'MOA', '']
[None, None, None, None, None, 'plant', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', None, None, None, '', 'Increase access to credit facilities', '', '', 'All camps, including the 14 earmarked', '', '', '1', '', '', '1', '', '', '1', '', '', '1', '', '', '1', '', '', 'MOA', '']
[None, None, None, None, '', None, None, None, 'for creation', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]

========== PDF PAGE 158 ==========

--- TABLE 1 ---
['', '', 'f) Irrigation', '', '', 'Construction of 3 dams', '', '', 'Muswishi block, Chisamba block,', '', '', '1', '', '', '', '', '', '1', '', '', '', '', '', '1', '', '', 'MOA, MWDS', '']
[None, None, 'development', None, '', None, None, None, 'Chankumba', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', '', None, None, '', 'Construction of 10 weirs', '', '', 'Lukoshi,Kanakantapa and Nalufwi,', '', '', '7', '', '', '', '', '', '1', '', '', '1', '', '', '1', '', '', 'MOA,', '']
[None, None, None, None, '', None, None, None, 'Lwamabwe, Momboshi, Kaputi,', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, None, 'C/PARTNERS', None]
[None, None, None, None, None, None, None, None, 'Lifwambula, Chikonkomene, Muswishi,', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '', None, None]
[None, None, None, None, None, None, None, None, 'Mulungushi Agro', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', '', 'g) Fisheries and', '', '', 'Enhance the participation of youth', '', '', '', '', '', '3', '', '', '3', '', '', '3', '', '', '3', '', '', '3', '', '', '', '']
[None, None, 'aquaculture', None, None, 'groups in aquaculture by linking 3', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, 'development', None, None, 'groups per year to CDF grants', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', '', None, None, '', 'Conduct 2 assessments of Fishery areas', '', '', 'Recommendation for assessment-', '', '', '', '', '', '1', '', '', '1', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'for breeding', None, None, 'Moroboshi dam and Mulungushi Agro', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, '', None, None, None, 'Dam', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', '', 'i) Livestock', '', '', 'To enhance Animal disease prevention', '', '', 'All veterinary camps', '', '', '5000', '', '', '50000', '', '', '50000', '', '', '50000', '', '', '5000', '', '', 'MFL', '']
[None, None, 'development', None, None, 'and control by vaccinating at least', None, '', None, None, None, '0', None, '', None, None, '', None, None, '', None, None, None, '0', None, '', None, None]
[None, '', None, None, None, '50,000 cattle against FMD yearly', None, None, None, None, '', None, None, None, None, None, None, None, None, None, None, None, '', None, None, None, None, None]
['', None, None, None, '', 'To enhance Animal disease prevention', '', '', 'All veterinary camps', '', '', '2000', '', '', '2000', '', '', '2000', '', '', '2000', '', '', '2000', '', '', 'MFL', '']
[None, None, None, None, None, 'and control by vaccinating at least 2000', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, 'calves against ECF yearly', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Conduct 5 sensitisation meetings to', '', '', 'All veterinary camps', '', '', '5', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'promote Animal Identification', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, 'registration-Brand Mark', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', '', 'j) Extension', '', '', 'Increase the number of agricultural', '', '', 'Subdivide Kanakantapa and', '', '', '9', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'MOA', '']
[None, None, 'services support', None, None, 'camps from the current 16 to 25 (Create', None, None, 'Chipembi into 3 camps each,', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, '', None, None, None, '9 more by subdividing the existing', None, None, 'Muswishi, Chowa, Bombwe,', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, 'camps)', None, None, 'Ploughmans B and Chikonkomene into', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, '', None, None, None, '2 camps each', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Create 2 more camps to Increase the', '', '', 'Subdivide Muswishi and Chipembi', '', '', '', '', '', '2', '', '', '', '', '', '', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, 'number of Veterinary camps from the', None, None, 'camps into 2 each', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, 'current 5 to 7 (by subdividing the existing', None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, 'camps)', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Increase the number of extension', '', '', 'All camps, including the 9 earmarked', '', '', '', '', '', '2', '', '', '2', '', '', '2', '', '', '', '', '', 'MOA', '']
[None, None, None, None, None, 'workers in the camps by employing 6', None, None, 'for creation', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, 'agricultural extension staff in addition to', None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, 'the current 19', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Employ 18 more extension staff under', '', '', 'All camps,', '', '', '2', '', '', '4', '', '', '4', '', '', '4', '', '', '4', '', '', 'MFL', '']
[None, None, None, None, None, 'fisheries and livestock (8 VAs & 10 LAs)', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, '', 'Procurement of 35 motorbikes for', '', '', 'All camps (Vet and Agric)', '', '', '', '', '', '5', '', '', '10', '', '', '10', '', '', '10', '', '', 'MOA/ MFL', '']
[None, None, None, None, None, 'agricultural and veterinary camp officers', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', None, None, None, '', 'Training of 5, 000 farmers in Climate', '', '', 'All camps, including the 9 earmarked', '', '', '1,000', '', '', '1,000', '', '', '1,000', '', '', '1,000', '', '', '1,000', '', '', 'MOA', '']

In [42]:
import pdfplumber
import pandas as pd

all_rows = []
with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    for page_num in range(155,160):
        page = pdf.pages[page_num]
        tables = page.extract_tables()
    for table in tables:
        for rows in table:
            all_rows.append([page_num + 1] + row)

idp_raw_df = pd.DataFrame(all_rows)
idp_raw_df.to_csv(
    "Chisamba_IDP_Implementaion_raw.csv", index=False)
print("Raw IDP extraction saved")
print("Rows:", len(idp_raw_df))
print("columns:", len(idp_raw_df.columns))

Raw IDP extraction saved
Rows: 39
columns: 34

In [43]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    page = pdf.pages[155]

    table = page.extract_table()

    for row in table:
        print(row)

['', 'ECONOMIC TRANSFORMATION AND JOB CREATION', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '']
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', 'Objective: To become an industrialised and diversified district by 2033', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '']
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', 'Strategies', '', '', 'Programmes', '', '', 'Sub Program', '', '', 'Location', '', '', 'YR 1', '', '', 'YR 2', '', '', 'YR 3', '', '', 'YR 4', '', '', 'YR 5', '', '', 'Responsible', '']
['', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
['', 'Improve', '', '', 'a)Infrastructure', '', '', 'Construction of 13 staff houses for', '', '', 'Chankumba and Chisamba blocks', '', '', '', '', '', '3', '', '', '3', '', '', '3', '', '', '4', '', '', 'MOA', '']
[None, 'Agricultural', None, None, 'Development', None, None, 'agricultural extension officers (2 for block', None, None, '', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, 'Production and', None, '', None, None, None, 'officers and 11 for camp officers)', None, None, 'Kanakantapa, Ploughman', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, 'Productivity', None, None, None, None, '', None, None, None, 'B,Chisamba', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['', None, None, None, None, None, None, None, None, None, 'central,Lwamabwe,Lukoshi,Lombwa,N', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, 'alufwi,Mulungushi', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, 'Agro,Mwapula,Kasosolo and', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, None, None, None, None, 'Mwantaya', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, '', 'Rehabilitation of 12 camp houses for', '', '', 'Ploughmans', '', '', '', '', '', '3', '', '', '3', '', '', '3', '', '', '3', '', '', 'MOA', '']
[None, None, None, None, None, None, None, 'agricultural extension officers', None, None, 'B,Chowa,Bombwe,Chikokomene,Lifwa', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', None, None, None, 'mbula/3,Muswishi/4 and Chipembi', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[None, None, None, None, None, None, '', 'Construction of 7 Veterinary camp', '', '', 'All veterinary camps', '', '', '', '', '', '1', '', '', '2', '', '', '2', '', '', '2', '', '', 'MFL', '']
[None, None, None, None, None, None, None, 'houses', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', 'Rehabilitation of 5 veterinary camp', '', '', '2 Lifwambula, 2 Chipembi, 1', '', '', '', '', '', '2', '', '', '1', '', '', '1', '', '', '1', '', '', 'MFL', '']
[None, None, None, None, None, None, None, 'houses', None, None, 'Chisamba central', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', 'Construction of 2 livestock service', '', '', 'Chisamba central and Muswishi', '', '', '', '', '', '1', '', '', '', '', '', '1', '', '', '', '', '', 'MFL', '']
[None, None, None, None, None, None, None, 'centers', None, None, 'camps', None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None, '', None, None]
[None, None, None, None, None, None, '', None, None, '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

In [44]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    page = pdf.pages[155]

    words = page.extract_words()

    for word in words[:100]:
        print(word)

{'text': '2.', 'x0': 101.54, 'x1': 111.464, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 9.923999999999992, 'direction': 'ltr'}
{'text': 'Reservation', 'x0': 119.06, 'x1': 186.584, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 67.524, 'direction': 'ltr'}
{'text': 'of', 'x0': 189.824, 'x1': 201.5, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 11.675999999999988, 'direction': 'ltr'}
{'text': 'land', 'x0': 204.692, 'x1': 231.01999999999998, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 26.327999999999975, 'direction': 'ltr'}
{'text': 'for', 'x0': 234.308, 'x1': 249.31999999999996, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 15.011999999999972, 'direction': 'ltr'}
{'text': 'future', 'x0': 252.65, 'x1': 286.466, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 33.816, 'direction': 'ltr'}
{'text': 'communication', 'x0': 289.718, 'x1': 382.418, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 92.69999999999999, 'direction': 'ltr'}
{'text': 'links', 'x0': 385.658, 'x1': 408.68600000000004, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 23.02800000000002, 'direction': 'ltr'}
{'text': 'in', 'x0': 411.92600000000004, 'x1': 421.646, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 9.71999999999997, 'direction': 'ltr'}
{'text': 'a', 'x0': 424.8860000000001, 'x1': 433.0820000000001, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 8.196000000000026, 'direction': 'ltr'}
{'text': 'manner', 'x0': 436.16600000000005, 'x1': 481.7660000000001, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 45.60000000000002, 'direction': 'ltr'}
{'text': 'that', 'x0': 485.09000000000003, 'x1': 508.61, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 23.519999999999982, 'direction': 'ltr'}
{'text': 'allows', 'x0': 511.826, 'x1': 547.442, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 35.615999999999985, 'direction': 'ltr'}
{'text': 'for', 'x0': 550.706, 'x1': 565.838, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 15.131999999999948, 'direction': 'ltr'}
{'text': 'building', 'x0': 569.066, 'x1': 615.518, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 46.452, 'direction': 'ltr'}
{'text': 'between', 'x0': 618.7220000000001, 'x1': 671.6180000000002, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 52.89600000000007, 'direction': 'ltr'}
{'text': 'existing', 'x0': 674.8580000000001, 'x1': 717.35, 'top': 74.75599999999997, 'doctop': 122294.756, 'bottom': 86.75599999999997, 'upright': True, 'height': 12.0, 'width': 42.49199999999996, 'direction': 'ltr'}
{'text': 'developments', 'x0': 119.54, 'x1': 203.36, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 83.82000000000001, 'direction': 'ltr'}
{'text': 'in', 'x0': 207.45200000000003, 'x1': 217.17200000000003, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 9.719999999999999, 'direction': 'ltr'}
{'text': 'order', 'x0': 221.24000000000004, 'x1': 252.32000000000002, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 31.079999999999984, 'direction': 'ltr'}
{'text': 'to', 'x0': 256.37600000000003, 'x1': 268.1960000000001, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 11.82000000000005, 'direction': 'ltr'}
{'text': 'make', 'x0': 272.20400000000006, 'x1': 305.5760000000001, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 33.372000000000014, 'direction': 'ltr'}
{'text': 'the', 'x0': 309.6200000000001, 'x1': 328.5800000000001, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 18.95999999999998, 'direction': 'ltr'}
{'text': 'areas', 'x0': 332.64800000000014, 'x1': 365.1320000000001, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 32.48399999999998, 'direction': 'ltr'}
{'text': 'denser', 'x0': 369.22400000000016, 'x1': 408.68000000000023, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 39.456000000000074, 'direction': 'ltr'}
{'text': 'and', 'x0': 412.64000000000027, 'x1': 436.3400000000003, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 23.700000000000045, 'direction': 'ltr'}
{'text': 'more', 'x0': 440.22800000000035, 'x1': 470.8280000000004, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 30.600000000000023, 'direction': 'ltr'}
{'text': 'efficient.', 'x0': 474.8840000000004, 'x1': 525.1040000000003, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 50.21999999999986, 'direction': 'ltr'}
{'text': 'Such', 'x0': 529.0880000000003, 'x1': 557.5040000000004, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 28.416000000000054, 'direction': 'ltr'}
{'text': 'reserves', 'x0': 561.5720000000003, 'x1': 608.1080000000004, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 46.53600000000006, 'direction': 'ltr'}
{'text': 'will', 'x0': 612.0800000000005, 'x1': 629.2280000000004, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 17.14799999999991, 'direction': 'ltr'}
{'text': 'serve', 'x0': 633.4040000000005, 'x1': 663.8840000000004, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 30.479999999999905, 'direction': 'ltr'}
{'text': 'to', 'x0': 667.9520000000003, 'x1': 679.6520000000004, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 11.700000000000045, 'direction': 'ltr'}
{'text': 'avoid', 'x0': 683.6600000000004, 'x1': 716.9480000000005, 'top': 91.67600000000004, 'doctop': 122311.676, 'bottom': 103.67599999999999, 'upright': True, 'height': 11.999999999999943, 'width': 33.288000000000125, 'direction': 'ltr'}
{'text': 'future', 'x0': 119.54, 'x1': 153.23600000000002, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 33.69600000000001, 'direction': 'ltr'}
{'text': 'transport', 'x0': 156.716, 'x1': 208.28, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 51.56399999999999, 'direction': 'ltr'}
{'text': 'problems', 'x0': 211.376, 'x1': 265.59200000000004, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 54.21600000000004, 'direction': 'ltr'}
{'text': 'and', 'x0': 268.82000000000005, 'x1': 292.55600000000004, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 23.73599999999999, 'direction': 'ltr'}
{'text': 'the', 'x0': 295.92800000000005, 'x1': 314.92400000000004, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 18.99599999999998, 'direction': 'ltr'}
{'text': 'additional', 'x0': 318.27200000000005, 'x1': 377.38400000000007, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 59.11200000000002, 'direction': 'ltr'}
{'text': 'cost', 'x0': 380.9360000000001, 'x1': 405.2840000000001, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 24.348000000000013, 'direction': 'ltr'}
{'text': 'of', 'x0': 408.4040000000001, 'x1': 420.0320000000001, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 11.627999999999986, 'direction': 'ltr'}
{'text': 'providing', 'x0': 423.2840000000001, 'x1': 478.0520000000002, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 54.768000000000086, 'direction': 'ltr'}
{'text': 'bulk', 'x0': 481.4840000000002, 'x1': 505.4960000000002, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 24.012, 'direction': 'ltr'}
{'text': 'municipal', 'x0': 508.7120000000002, 'x1': 566.11, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 57.3979999999998, 'direction': 'ltr'}
{'text': 'services;', 'x0': 569.578, 'x1': 618.226, 'top': 108.596, 'doctop': 122328.596, 'bottom': 120.596, 'upright': True, 'height': 12.0, 'width': 48.648000000000025, 'direction': 'ltr'}
{'text': '3.', 'x0': 101.54, 'x1': 111.464, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 9.923999999999992, 'direction': 'ltr'}
{'text': 'Increase', 'x0': 119.06, 'x1': 168.93200000000002, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 49.872000000000014, 'direction': 'ltr'}
{'text': 'the', 'x0': 172.304, 'x1': 191.264, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 18.960000000000008, 'direction': 'ltr'}
{'text': 'population', 'x0': 194.612, 'x1': 258.416, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 63.804, 'direction': 'ltr'}
{'text': 'densities', 'x0': 261.74, 'x1': 310.94000000000005, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 49.200000000000045, 'direction': 'ltr'}
{'text': 'through', 'x0': 314.4320000000001, 'x1': 359.80400000000003, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 45.37199999999996, 'direction': 'ltr'}
{'text': 'effective', 'x0': 363.2600000000001, 'x1': 414.9560000000001, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 51.69599999999997, 'direction': 'ltr'}
{'text': 'land', 'x0': 418.3040000000001, 'x1': 444.5120000000001, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 26.208000000000027, 'direction': 'ltr'}
{'text': 'use', 'x0': 447.8840000000001, 'x1': 467.68400000000014, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 19.80000000000001, 'direction': 'ltr'}
{'text': 'zoning', 'x0': 470.91200000000015, 'x1': 508.90400000000017, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 37.99200000000002, 'direction': 'ltr'}
{'text': 'where', 'x0': 512.2280000000002, 'x1': 548.8280000000002, 'top': 133.55599999999998, 'doctop': 122353.556, 'bottom': 145.55599999999998, 'upright': True, 'height': 12.0, 'width': 36.60000000000002, 'direction': 'ltr'}
{'text': 'Residential', 'x0': 118.22, 'x1': 180.584, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 62.364000000000004, 'direction': 'ltr'}
{'text': 'areas', 'x0': 184.51999999999998, 'x1': 216.896, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 32.376000000000005, 'direction': 'ltr'}
{'text': 'and', 'x0': 220.50799999999998, 'x1': 244.20799999999997, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 23.69999999999999, 'direction': 'ltr'}
{'text': 'farms', 'x0': 247.96399999999997, 'x1': 279.488, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 31.52400000000003, 'direction': 'ltr'}
{'text': 'are', 'x0': 283.21999999999997, 'x1': 302.792, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 19.572000000000003, 'direction': 'ltr'}
{'text': 'arranged', 'x0': 306.488, 'x1': 361.53200000000004, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 55.04400000000004, 'direction': 'ltr'}
{'text': 'under', 'x0': 365.264, 'x1': 399.584, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 34.31999999999999, 'direction': 'ltr'}
{'text': 'group', 'x0': 403.2800000000001, 'x1': 438.2000000000001, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 34.920000000000016, 'direction': 'ltr'}
{'text': 'use.', 'x0': 441.90800000000013, 'x1': 465.02000000000015, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 23.112000000000023, 'direction': 'ltr'}
{'text': 'Mixed-use', 'x0': 468.64400000000023, 'x1': 528.0699999999999, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 59.4259999999997, 'direction': 'ltr'}
{'text': 'developments', 'x0': 531.79, 'x1': 615.4899999999999, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 83.69999999999993, 'direction': 'ltr'}
{'text': 'to', 'x0': 619.342, 'x1': 631.162, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 11.82000000000005, 'direction': 'ltr'}
{'text': 'be', 'x0': 634.81, 'x1': 650.7939999999999, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 15.983999999999924, 'direction': 'ltr'}
{'text': 'created', 'x0': 654.478, 'x1': 702.01, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 47.53200000000004, 'direction': 'ltr'}
{'text': 'on', 'x0': 705.766, 'x1': 720.8860000000001, 'top': 150.476, 'doctop': 122370.476, 'bottom': 162.476, 'upright': True, 'height': 12.0, 'width': 15.120000000000118, 'direction': 'ltr'}
{'text': 'basis', 'x0': 101.54, 'x1': 129.572, 'top': 167.39599999999996, 'doctop': 122387.396, 'bottom': 179.39599999999996, 'upright': True, 'height': 12.0, 'width': 28.031999999999996, 'direction': 'ltr'}
{'text': 'of', 'x0': 132.93200000000002, 'x1': 144.56000000000003, 'top': 167.39599999999996, 'doctop': 122387.396, 'bottom': 179.39599999999996, 'upright': True, 'height': 12.0, 'width': 11.628000000000014, 'direction': 'ltr'}
{'text': 'compatibility', 'x0': 147.812, 'x1': 223.472, 'top': 167.39599999999996, 'doctop': 122387.396, 'bottom': 179.39599999999996, 'upright': True, 'height': 12.0, 'width': 75.66, 'direction': 'ltr'}
{'text': 'of', 'x0': 226.83200000000005, 'x1': 238.46000000000006, 'top': 167.39599999999996, 'doctop': 122387.396, 'bottom': 179.39599999999996, 'upright': True, 'height': 12.0, 'width': 11.628000000000014, 'direction': 'ltr'}
{'text': 'function;', 'x0': 241.71200000000005, 'x1': 292.8080000000001, 'top': 167.39599999999996, 'doctop': 122387.396, 'bottom': 179.39599999999996, 'upright': True, 'height': 12.0, 'width': 51.09600000000006, 'direction': 'ltr'}
{'text': 'and', 'x0': 296.0480000000001, 'x1': 319.7840000000001, 'top': 167.39599999999996, 'doctop': 122387.396, 'bottom': 179.39599999999996, 'upright': True, 'height': 12.0, 'width': 23.73599999999999, 'direction': 'ltr'}
{'text': '4.', 'x0': 101.54, 'x1': 111.464, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 9.923999999999992, 'direction': 'ltr'}
{'text': 'Increase', 'x0': 119.06, 'x1': 168.93200000000002, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 49.872000000000014, 'direction': 'ltr'}
{'text': 'access', 'x0': 174.10399999999998, 'x1': 214.952, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 40.84800000000001, 'direction': 'ltr'}
{'text': 'to', 'x0': 220.136, 'x1': 231.836, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 11.700000000000017, 'direction': 'ltr'}
{'text': 'services', 'x0': 237.02, 'x1': 282.45200000000006, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 45.432000000000045, 'direction': 'ltr'}
{'text': 'through', 'x0': 287.744, 'x1': 332.996, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 45.25199999999995, 'direction': 'ltr'}
{'text': 'land', 'x0': 338.13199999999995, 'x1': 364.46000000000004, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 26.328000000000088, 'direction': 'ltr'}
{'text': 'allocations', 'x0': 369.548, 'x1': 432.47600000000006, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 62.928000000000054, 'direction': 'ltr'}
{'text': 'that', 'x0': 437.76800000000003, 'x1': 461.384, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 23.615999999999985, 'direction': 'ltr'}
{'text': 'take', 'x0': 466.5440000000001, 'x1': 492.57200000000006, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 26.027999999999963, 'direction': 'ltr'}
{'text': 'into', 'x0': 497.72000000000014, 'x1': 519.248, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 21.527999999999906, 'direction': 'ltr'}
{'text': 'account', 'x0': 524.3360000000001, 'x1': 574.6880000000001, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 50.351999999999975, 'direction': 'ltr'}
{'text': 'social', 'x0': 579.7280000000002, 'x1': 612.9440000000002, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 33.21600000000001, 'direction': 'ltr'}
{'text': 'services,', 'x0': 618.3200000000002, 'x1': 666.9680000000002, 'top': 201.26599999999996, 'doctop': 122421.266, 'bottom': 213.26599999999996, 'upright': True, 'height': 12.0, 'width': 48.648000000000025, 'direction': 'ltr'}

In [45]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    page = pdf.pages[155]
    print(page.extract_text())

2. Reservation of land for future communication links in a manner that allows for building between existing
developments in order to make the areas denser and more efficient. Such reserves will serve to avoid
future transport problems and the additional cost of providing bulk municipal services;
3. Increase the population densities through effective land use zoning where
Residential areas and farms are arranged under group use. Mixed-use developments to be created on
basis of compatibility of function; and
4. Increase access to services through land allocations that take into account social services, such as
education, health, open spaces and areas for public facilities.
ECONOMIC TRANSFORMATION AND JOB CREATION
Objective: To become an industrialised and diversified district by 2033
Strategies Programmes Sub Program Location YR 1 YR 2 YR 3 YR 4 YR 5 Responsible
Improve a)Infrastructure Construction of 13 staff houses for Chankumba and Chisamba blocks 3 3 3 4 MOA
Agricultural Development agricultural extension officers (2 for block
Production and officers and 11 for camp officers) Kanakantapa, Ploughman
Productivity B,Chisamba
central,Lwamabwe,Lukoshi,Lombwa,N
alufwi,Mulungushi
Agro,Mwapula,Kasosolo and
Mwantaya
Rehabilitation of 12 camp houses for Ploughmans 3 3 3 3 MOA
agricultural extension officers B,Chowa,Bombwe,Chikokomene,Lifwa
mbula/3,Muswishi/4 and Chipembi
Construction of 7 Veterinary camp All veterinary camps 1 2 2 2 MFL
houses
Rehabilitation of 5 veterinary camp 2 Lifwambula, 2 Chipembi, 1 2 1 1 1 MFL
houses Chisamba central
Construction of 2 livestock service Chisamba central and Muswishi 1 1 MFL
centers camps
138

In [46]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    for page_num in range(155, 160):
        text = pdf.pages[page_num].extract_text()

        with open(f"IDP_page_{page_num + 1}_raw.txt", "w", encoding="utf-8") as f:
            f.write(text)

print("Raw IDP pages saved")

Raw IDP pages saved

In [47]:
with open("IDP_page_156_raw.txt", "r", encoding="utf-8") as f:
    text = f.read()

print(text)

2. Reservation of land for future communication links in a manner that allows for building between existing
developments in order to make the areas denser and more efficient. Such reserves will serve to avoid
future transport problems and the additional cost of providing bulk municipal services;
3. Increase the population densities through effective land use zoning where
Residential areas and farms are arranged under group use. Mixed-use developments to be created on
basis of compatibility of function; and
4. Increase access to services through land allocations that take into account social services, such as
education, health, open spaces and areas for public facilities.
ECONOMIC TRANSFORMATION AND JOB CREATION
Objective: To become an industrialised and diversified district by 2033
Strategies Programmes Sub Program Location YR 1 YR 2 YR 3 YR 4 YR 5 Responsible
Improve a)Infrastructure Construction of 13 staff houses for Chankumba and Chisamba blocks 3 3 3 4 MOA
Agricultural Development agricultural extension officers (2 for block
Production and officers and 11 for camp officers) Kanakantapa, Ploughman
Productivity B,Chisamba
central,Lwamabwe,Lukoshi,Lombwa,N
alufwi,Mulungushi
Agro,Mwapula,Kasosolo and
Mwantaya
Rehabilitation of 12 camp houses for Ploughmans 3 3 3 3 MOA
agricultural extension officers B,Chowa,Bombwe,Chikokomene,Lifwa
mbula/3,Muswishi/4 and Chipembi
Construction of 7 Veterinary camp All veterinary camps 1 2 2 2 MFL
houses
Rehabilitation of 5 veterinary camp 2 Lifwambula, 2 Chipembi, 1 2 1 1 1 MFL
houses Chisamba central
Construction of 2 livestock service Chisamba central and Muswishi 1 1 MFL
centers camps
138

In [48]:
text = text.split(
    "Strategies Programmes Sub Program Location YR 1 YR 2 YR 3 YR 4 YR 5 Responsible",
    1
)[1]

print(text)

Improve a)Infrastructure Construction of 13 staff houses for Chankumba and Chisamba blocks 3 3 3 4 MOA
Agricultural Development agricultural extension officers (2 for block
Production and officers and 11 for camp officers) Kanakantapa, Ploughman
Productivity B,Chisamba
central,Lwamabwe,Lukoshi,Lombwa,N
alufwi,Mulungushi
Agro,Mwapula,Kasosolo and
Mwantaya
Rehabilitation of 12 camp houses for Ploughmans 3 3 3 3 MOA
agricultural extension officers B,Chowa,Bombwe,Chikokomene,Lifwa
mbula/3,Muswishi/4 and Chipembi
Construction of 7 Veterinary camp All veterinary camps 1 2 2 2 MFL
houses
Rehabilitation of 5 veterinary camp 2 Lifwambula, 2 Chipembi, 1 2 1 1 1 MFL
houses Chisamba central
Construction of 2 livestock service Chisamba central and Muswishi 1 1 MFL
centers camps
138

In [49]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    page = pdf.pages[155]

    words = page.extract_words()

    for word in words:
        if 200 < word["top"] < 430:
            print(
                word["text"],
                "x0=", round(word["x0"], 1),
                "top=", round(word["top"], 1)
            )

4. x0= 101.5 top= 201.3
Increase x0= 119.1 top= 201.3
access x0= 174.1 top= 201.3
to x0= 220.1 top= 201.3
services x0= 237.0 top= 201.3
through x0= 287.7 top= 201.3
land x0= 338.1 top= 201.3
allocations x0= 369.5 top= 201.3
that x0= 437.8 top= 201.3
take x0= 466.5 top= 201.3
into x0= 497.7 top= 201.3
account x0= 524.3 top= 201.3
social x0= 579.7 top= 201.3
services, x0= 618.3 top= 201.3
such x0= 672.1 top= 201.3
as x0= 704.3 top= 201.3
education, x0= 119.5 top= 218.2
health, x0= 186.9 top= 218.2
open x0= 230.7 top= 218.2
spaces x0= 265.2 top= 218.2
and x0= 309.9 top= 218.2
areas x0= 336.9 top= 218.2
for x0= 372.6 top= 218.2
public x0= 391.1 top= 218.2
facilities. x0= 430.7 top= 218.2
ECONOMIC x0= 28.1 top= 268.4
TRANSFORMATION x0= 75.8 top= 268.4
AND x0= 148.5 top= 268.4
JOB x0= 168.3 top= 268.4
CREATION x0= 185.7 top= 268.4
Objective: x0= 28.1 top= 283.8
To x0= 70.9 top= 283.8
become x0= 81.8 top= 283.8
an x0= 117.8 top= 283.8
industrialised x0= 130.3 top= 283.8
and x0= 181.6 top= 283.8
diversified x0= 199.7 top= 283.8
district x0= 240.5 top= 283.8
by x0= 267.5 top= 283.8
2033 x0= 279.6 top= 283.8
Strategies x0= 28.1 top= 299.3
Programmes x0= 106.1 top= 299.3
Sub x0= 184.1 top= 299.3
Program x0= 200.7 top= 299.3
Location x0= 354.4 top= 299.3
YR x0= 517.1 top= 299.3
1 x0= 529.0 top= 299.3
YR x0= 550.3 top= 299.3
2 x0= 562.1 top= 299.3
YR x0= 590.9 top= 299.3
3 x0= 602.7 top= 299.3
YR x0= 626.9 top= 299.3
4 x0= 638.7 top= 299.3
YR x0= 662.9 top= 299.3
5 x0= 674.7 top= 299.3
Responsible x0= 694.3 top= 299.3
Improve x0= 28.1 top= 314.8
a)Infrastructure x0= 106.1 top= 314.8
Construction x0= 184.1 top= 314.8
of x0= 235.7 top= 314.8
13 x0= 245.6 top= 314.8
staff x0= 256.8 top= 314.8
houses x0= 275.2 top= 314.8
for x0= 303.9 top= 314.8
Chankumba x0= 354.4 top= 314.8
and x0= 405.7 top= 314.8
Chisamba x0= 423.7 top= 314.8
blocks x0= 466.0 top= 314.8
3 x0= 550.3 top= 314.8
3 x0= 590.9 top= 314.8
3 x0= 626.9 top= 314.8
4 x0= 662.9 top= 314.8
MOA x0= 694.3 top= 314.8
Agricultural x0= 28.1 top= 326.1
Development x0= 106.1 top= 326.1
agricultural x0= 184.1 top= 326.1
extension x0= 229.9 top= 326.1
officers x0= 268.8 top= 326.1
(2 x0= 298.8 top= 326.1
for x0= 308.3 top= 326.1
block x0= 320.7 top= 326.1
Production x0= 28.1 top= 337.4
and x0= 72.7 top= 337.4
officers x0= 184.1 top= 337.4
and x0= 214.1 top= 337.4
11 x0= 232.2 top= 337.4
for x0= 243.3 top= 337.4
camp x0= 255.7 top= 337.4
officers) x0= 281.4 top= 337.4
Kanakantapa, x0= 354.4 top= 337.4
Ploughman x0= 412.8 top= 337.4
Productivity x0= 28.1 top= 348.7
B,Chisamba x0= 354.4 top= 348.7
central,Lwamabwe,Lukoshi,Lombwa,N x0= 354.4 top= 359.9
alufwi,Mulungushi x0= 354.4 top= 371.2
Agro,Mwapula,Kasosolo x0= 354.4 top= 382.5
and x0= 450.6 top= 382.5
Mwantaya x0= 354.4 top= 393.8
Rehabilitation x0= 184.1 top= 405.5
of x0= 239.6 top= 405.5
12 x0= 251.8 top= 405.5
camp x0= 262.9 top= 405.5
houses x0= 288.7 top= 405.5
for x0= 317.3 top= 405.5
Ploughmans x0= 354.4 top= 405.5
3 x0= 550.3 top= 405.5
3 x0= 590.9 top= 405.5
3 x0= 626.9 top= 405.5
3 x0= 662.9 top= 405.5
MOA x0= 694.3 top= 405.5
agricultural x0= 184.1 top= 416.8
extension x0= 229.9 top= 416.8
officers x0= 268.9 top= 416.8
B,Chowa,Bombwe,Chikokomene,Lifwa x0= 354.4 top= 416.8
mbula/3,Muswishi/4 x0= 354.4 top= 428.1
and x0= 432.7 top= 428.1
Chipembi x0= 450.8 top= 428.1

In [50]:
import pdfplumber

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    page = pdf.pages[155]

    words = page.extract_words()

    table_words = [
        w for w in words
        if 299 < w["top"] < 500
    ]

    for w in table_words:
        print(
            w["text"],
            "| x0 =", round(w["x0"], 1),
            "| top =", round(w["top"], 1)
        )

Strategies | x0 = 28.1 | top = 299.3
Programmes | x0 = 106.1 | top = 299.3
Sub | x0 = 184.1 | top = 299.3
Program | x0 = 200.7 | top = 299.3
Location | x0 = 354.4 | top = 299.3
YR | x0 = 517.1 | top = 299.3
1 | x0 = 529.0 | top = 299.3
YR | x0 = 550.3 | top = 299.3
2 | x0 = 562.1 | top = 299.3
YR | x0 = 590.9 | top = 299.3
3 | x0 = 602.7 | top = 299.3
YR | x0 = 626.9 | top = 299.3
4 | x0 = 638.7 | top = 299.3
YR | x0 = 662.9 | top = 299.3
5 | x0 = 674.7 | top = 299.3
Responsible | x0 = 694.3 | top = 299.3
Improve | x0 = 28.1 | top = 314.8
a)Infrastructure | x0 = 106.1 | top = 314.8
Construction | x0 = 184.1 | top = 314.8
of | x0 = 235.7 | top = 314.8
13 | x0 = 245.6 | top = 314.8
staff | x0 = 256.8 | top = 314.8
houses | x0 = 275.2 | top = 314.8
for | x0 = 303.9 | top = 314.8
Chankumba | x0 = 354.4 | top = 314.8
and | x0 = 405.7 | top = 314.8
Chisamba | x0 = 423.7 | top = 314.8
blocks | x0 = 466.0 | top = 314.8
3 | x0 = 550.3 | top = 314.8
3 | x0 = 590.9 | top = 314.8
3 | x0 = 626.9 | top = 314.8
4 | x0 = 662.9 | top = 314.8
MOA | x0 = 694.3 | top = 314.8
Agricultural | x0 = 28.1 | top = 326.1
Development | x0 = 106.1 | top = 326.1
agricultural | x0 = 184.1 | top = 326.1
extension | x0 = 229.9 | top = 326.1
officers | x0 = 268.8 | top = 326.1
(2 | x0 = 298.8 | top = 326.1
for | x0 = 308.3 | top = 326.1
block | x0 = 320.7 | top = 326.1
Production | x0 = 28.1 | top = 337.4
and | x0 = 72.7 | top = 337.4
officers | x0 = 184.1 | top = 337.4
and | x0 = 214.1 | top = 337.4
11 | x0 = 232.2 | top = 337.4
for | x0 = 243.3 | top = 337.4
camp | x0 = 255.7 | top = 337.4
officers) | x0 = 281.4 | top = 337.4
Kanakantapa, | x0 = 354.4 | top = 337.4
Ploughman | x0 = 412.8 | top = 337.4
Productivity | x0 = 28.1 | top = 348.7
B,Chisamba | x0 = 354.4 | top = 348.7
central,Lwamabwe,Lukoshi,Lombwa,N | x0 = 354.4 | top = 359.9
alufwi,Mulungushi | x0 = 354.4 | top = 371.2
Agro,Mwapula,Kasosolo | x0 = 354.4 | top = 382.5
and | x0 = 450.6 | top = 382.5
Mwantaya | x0 = 354.4 | top = 393.8
Rehabilitation | x0 = 184.1 | top = 405.5
of | x0 = 239.6 | top = 405.5
12 | x0 = 251.8 | top = 405.5
camp | x0 = 262.9 | top = 405.5
houses | x0 = 288.7 | top = 405.5
for | x0 = 317.3 | top = 405.5
Ploughmans | x0 = 354.4 | top = 405.5
3 | x0 = 550.3 | top = 405.5
3 | x0 = 590.9 | top = 405.5
3 | x0 = 626.9 | top = 405.5
3 | x0 = 662.9 | top = 405.5
MOA | x0 = 694.3 | top = 405.5
agricultural | x0 = 184.1 | top = 416.8
extension | x0 = 229.9 | top = 416.8
officers | x0 = 268.9 | top = 416.8
B,Chowa,Bombwe,Chikokomene,Lifwa | x0 = 354.4 | top = 416.8
mbula/3,Muswishi/4 | x0 = 354.4 | top = 428.1
and | x0 = 432.7 | top = 428.1
Chipembi | x0 = 450.8 | top = 428.1
Construction | x0 = 184.1 | top = 440.0
of | x0 = 235.7 | top = 440.0
7 | x0 = 247.9 | top = 440.0
Veterinary | x0 = 254.5 | top = 440.0
camp | x0 = 296.5 | top = 440.0
All | x0 = 354.4 | top = 440.0
veterinary | x0 = 365.8 | top = 440.0
camps | x0 = 406.7 | top = 440.0
1 | x0 = 550.3 | top = 440.0
2 | x0 = 590.9 | top = 440.0
2 | x0 = 626.9 | top = 440.0
2 | x0 = 662.9 | top = 440.0
MFL | x0 = 694.3 | top = 440.0
houses | x0 = 184.1 | top = 451.3
Rehabilitation | x0 = 184.1 | top = 465.0
of | x0 = 239.6 | top = 465.0
5 | x0 = 249.6 | top = 465.0
veterinary | x0 = 256.3 | top = 465.0
camp | x0 = 297.1 | top = 465.0
2 | x0 = 354.4 | top = 465.0
Lifwambula, | x0 = 361.1 | top = 465.0
2 | x0 = 410.4 | top = 465.0
Chipembi, | x0 = 417.0 | top = 465.0
1 | x0 = 459.6 | top = 465.0
2 | x0 = 550.3 | top = 465.0
1 | x0 = 590.9 | top = 465.0
1 | x0 = 626.9 | top = 465.0
1 | x0 = 662.9 | top = 465.0
MFL | x0 = 694.3 | top = 465.0
houses | x0 = 184.1 | top = 476.3
Chisamba | x0 = 354.4 | top = 476.3
central | x0 = 396.8 | top = 476.3
Construction | x0 = 184.1 | top = 488.0
of | x0 = 235.7 | top = 488.0
2 | x0 = 245.6 | top = 488.0
livestock | x0 = 252.2 | top = 488.0
service | x0 = 287.6 | top = 488.0
Chisamba | x0 = 354.4 | top = 488.0
central | x0 = 396.8 | top = 488.0
and | x0 = 426.3 | top = 488.0
Muswishi | x0 = 444.3 | top = 488.0
1 | x0 = 550.3 | top = 488.0
1 | x0 = 626.9 | top = 488.0
MFL | x0 = 694.3 | top = 488.0
centers | x0 = 184.1 | top = 499.3
camps | x0 = 354.4 | top = 499.3

In [51]:
import pdfplumber
import pandas as pd

columns = {
    "Strategies": (0, 106),
    "Programmes": (106, 184),
    "Sub Program": (184, 354),
    "Location": (354, 517),
    "YR 1": (517, 550),
    "YR 2": (550, 591),
    "YR 3": (591, 627),
    "YR 4": (627, 663),
    "YR 5": (663, 694),
    "Responsible": (694, 800)
}

rows = []

with pdfplumber.open("IDP_2024_2034.pdf") as pdf:
    page = pdf.pages[155]
    words = page.extract_words()

    for top in sorted(set(round(w["top"], 1) for w in words)):
        row_words = [w for w in words if round(w["top"], 1) == top]

        row = {}

        for column, (xmin, xmax) in columns.items():
            selected = [
                w["text"]
                for w in row_words
                if xmin <= w["x0"] < xmax
            ]

            row[column] = " ".join(selected)

        if any(row.values()):
            rows.append(row)

df_test = pd.DataFrame(rows)

print(df_test.to_string(index=False))

             Strategies            Programmes                                  Sub Program                          Location         YR 1         YR 2      YR 3       YR 4     YR 5 Responsible
                     2.           Reservation             of land for future communication     links in a manner that allows              for building   between            existing
                                 developments                   in order to make the areas        denser and more efficient.         Such     reserves      will      serve to avoid
                             future transport                  problems and the additional  cost of providing bulk municipal                 services;
                     3.          Increase the                 population densities through   effective land use zoning where
                                  Residential                 areas and farms are arranged        under group use. Mixed-use developments                     to be created                   on
                  basis      of compatibility                             of function; and
                     4.       Increase access                     to services through land        allocations that take into      account       social services,                such          as
                                   education,                health, open spaces and areas            for public facilities.
ECONOMIC TRANSFORMATION               AND JOB                                     CREATION
   Objective: To become an industrialised and                 diversified district by 2033
             Strategies            Programmes                                  Sub Program                          Location         YR 1      YR 2 YR      3 YR       4 YR        5 Responsible
                Improve      a)Infrastructure          Construction of 13 staff houses for     Chankumba and Chisamba blocks                       3 3         3          4                  MOA
           Agricultural           Development agricultural extension officers (2 for block
         Production and                                 officers and 11 for camp officers)            Kanakantapa, Ploughman
           Productivity                                                                                           B,Chisamba
                                                                                           central,Lwamabwe,Lukoshi,Lombwa,N
                                                                                                           alufwi,Mulungushi
                                                                                                   Agro,Mwapula,Kasosolo and
                                                                                                                    Mwantaya
                                                      Rehabilitation of 12 camp houses for                        Ploughmans                       3 3         3          3                  MOA
                                                           agricultural extension officers  B,Chowa,Bombwe,Chikokomene,Lifwa
                                                                                             mbula/3,Muswishi/4 and Chipembi
                                                         Construction of 7 Veterinary camp              All veterinary camps                       1 2         2          2                  MFL
                                                                                    houses
                                                       Rehabilitation of 5 veterinary camp       2 Lifwambula, 2 Chipembi, 1                       2 1         1          1                  MFL
                                                                                    houses                  Chisamba central
                                                       Construction of 2 livestock service     Chisamba central and Muswishi                         1         1                             MFL
                                                                                   centers                             camps
                                                                                                                                                                                             138

In [52]:
import camelot
print(camelot.__version__)

2.0.0

In [53]:
import camelot

tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="156",
    flavor="stream"
)

print("Tables found:", tables.n)

Tables found: 1

In [54]:
print(tables[0].df.to_string(index=False))

                                                                      0                1                                                               2                                 3    4    5    6    7    8           9
                                                                                         education, health, open spaces and areas for public facilities.
                               ECONOMIC TRANSFORMATION AND JOB CREATION
Objective: To become an industrialised and diversified district by 2033
                                                             Strategies       Programmes                                                     Sub Program                          Location YR 1 YR 2 YR 3 YR 4 YR 5 Responsible
                                                                Improve a)Infrastructure                             Construction of 13 staff houses for     Chankumba and Chisamba blocks         3    3    3    4         MOA
                                                           Agricultural      Development                    agricultural extension officers (2 for block
                                                         Production and                                               officers and 11 for camp officers)            Kanakantapa, Ploughman
                                                           Productivity                                                                                                         B,Chisamba
                                                                                                                                                         central,Lwamabwe,Lukoshi,Lombwa,N
                                                                                                                                                                         alufwi,Mulungushi
                                                                                                                                                                 Agro,Mwapula,Kasosolo and
                                                                                                                                                                                  Mwantaya
                                                                                                                   Rehabilitation of  12 camp houses for                        Ploughmans         3    3    3    3         MOA
                                                                                                                         agricultural extension officers  B,Chowa,Bombwe,Chikokomene,Lifwa
                                                                                                                                                           mbula/3,Muswishi/4 and Chipembi
                                                                                                                      Construction of  7 Veterinary camp              All veterinary camps         1    2    2    2         MFL
                                                                                                                                                  houses
                                                                                                                     Rehabilitation of 5 veterinary camp       2 Lifwambula, 2 Chipembi, 1         2    1    1    1         MFL
                                                                                                                                                  houses                  Chisamba central
                                                                                                                     Construction of 2 livestock service     Chisamba central and Muswishi         1         1              MFL
                                                                                                                                                 centers                             camps

In [55]:
tables_lattice = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="156",
    flavor="lattice"
)

print("Tables found:", tables_lattice.n)

if tables_lattice.n > 0:
    print(tables_lattice[0].df.to_string(index=False))

Tables found: 1
                                                                      0                              1                                                                                                                       2                                                                                                                                                                     3    4    5    6    7    8           9
                               ECONOMIC TRANSFORMATION AND JOB CREATION
Objective: To become an industrialised and diversified district by 2033
                                                             Strategies                     Programmes                                                                                                             Sub Program                                                                                                                                                              Location YR 1 YR 2 YR 3 YR 4 YR 5 Responsible
                 Improve \nAgricultural \nProduction and \nProductivity a)Infrastructure \nDevelopment Construction of 13 staff houses for \nagricultural extension officers (2 for block \nofficers and 11 for camp officers) Chankumba and Chisamba blocks \n  \nKanakantapa, Ploughman \nB,Chisamba \ncentral,Lwamabwe,Lukoshi,Lombwa,N\nalufwi,Mulungushi \nAgro,Mwapula,Kasosolo and \nMwantaya         3    3    3    4         MOA
                                                                                                                                                       Rehabilitation of  12 camp houses for \nagricultural extension officers                                                                                        Ploughmans \nB,Chowa,Bombwe,Chikokomene,Lifwa\nmbula/3,Muswishi/4 and Chipembi         3    3    3    3         MOA
                                                                                                                                                                                   Construction of  7 Veterinary camp \nhouses                                                                                                                                                  All veterinary camps         1    2    2    2         MFL
                                                                                                                                                                                  Rehabilitation of 5 veterinary camp \nhouses                                                                                                                        2 Lifwambula, 2 Chipembi, 1 \nChisamba central         2    1    1    1         MFL
                                                                                                                                                                                 Construction of 2 livestock service \ncenters                                                                                                                                 Chisamba central and Muswishi \ncamps         1         1              MFL

In [56]:
tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="157",
    flavor="lattice"
)

print("Tables found:", tables.n)

if tables.n > 0:
    print(tables[0].df.to_string(index=False))

Tables found: 1
0                              1                                                                                                          2                                                                             3                    4                5     6     7       8               9
                                                                              Construction of Animal Health \nInfrastructure( 16 Dip tanks) 3 Chisamba Central, 3 chisamba \nwest,  4 lifwambula, 3 muswishi,3 \nchipembi                                     4     4     4       4             MFL
                                                                                              Construction of 1 livestock breeding \ncenter                                                                 Muswishi camp                                           1                           MFL
                                                                                                Construction of 1 Livestock market \ncenter                                        Chisamba west camp-John chinena \narea                                     1                                 MLF
                                                                                                     Construction of 2 Slaughter facilities                      Chisamba west camp-John chinena \narea and Muswishi camp                                           1             1          LA/MFL
                                                                                                            Construction of 3 storage sheds                                               Kanakantapa, Nalufwi and Bombwe                                           1     1       1             MOA
                                                                                           Construction of a fingerling production \ncentre                                                                  New chisamba                                           1                           MFL
                                                                                              Construction of fish feed production \ncentre                                                                  New chisamba                                                         1             MFL
  b)Agricultural \nmechanisation Increase access to mechanisation by \nfarmers by linking farmers to partners \nsuch as equipment suppliers                          All camps, including the 14 earmarked \nfor creation                    1                1     1     1       1 MOA, \nPARTNERS
     c)Enhanced \nfarmer support                                     Provision of Farmer Input Support to \nfarmers under the FISP to 16416                          All camps, including the 14 earmarked \nfor creation              1641\n6            16416 16416 16416 1641\n6             MOA
   e) Agribusiness \ndevelopment                                       Conduct 30 sensitization meetings on \nagricultural marketing system   Nalufwi, Chowa, Chisamba central, \nLifwambula, Chisamba ranch and \nKamano                    6                6     6     6       6             MOA
                                             Conduct 5 sensitization meetings to \npromote  Animal Identification \nregistration-Brand Mark                                                          All veterinary camps                    5                                                  MFL
                                                                    Training of 1506 Livestock farmers in \nlivestock farming as a business              Muswishi, Chipembi, Lifambula, \nChisamba Central, Chisamba west                                   556   500   450                     MFL
                                                Training of 20 individual fish farmers and \n4 cooperatives in fish farming as a \nbusiness                                                                     All wards 4 \nCoo\nperat\nives 20 ind \nfarmers                                 MFL
                                                                        Establishment of 3 value chains while \nstrengthening existing ones                            Momboshi, Chipembi, Chankumba \nand Muswishi camps                                     1     1     1                MOA/ MFL
                                                                                               Establishment of one Agro processing \nplant                                                               Chankumba block                                                 1                     MOA
                                                                                                       Increase access to credit facilities                          All camps, including the 14 earmarked \nfor creation                    1                1     1     1       1             MOA

In [57]:
import camelot
import pandas as pd

tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="156-160",
    flavor="lattice"
)

all_tables = []

for i, table in enumerate(tables):
    df = table.df.copy()
    df.insert(0, "Source_Page", table.page)
    df.insert(1, "Table_Number", i + 1)
    all_tables.append(df)

raw_idp = pd.concat(all_tables, ignore_index=True)

raw_idp.to_csv(
    "Chisamba_IDP_Development_Framework_raw_156_160.csv",
    index=False
)

print("Tables extracted:", len(tables))
print("Raw rows:", len(raw_idp))
print("Raw columns:", len(raw_idp.columns))
print("Saved successfully.")

Tables extracted: 5
Raw rows: 56
Raw columns: 13
Saved successfully.

In [58]:
print(raw_idp.head(10).to_string(index=False))

 Source_Page  Table_Number                                                                       0                              1                                                                                                                       2                                                                                                                                                                     3    4    5    6    7    8           9  10
         156             1                                ECONOMIC TRANSFORMATION AND JOB CREATION                                                                                                                                                                                                                                                                                                                                                                   NaN
         156             1 Objective: To become an industrialised and diversified district by 2033                                                                                                                                                                                                                                                                                                                                                                   NaN
         156             1                                                              Strategies                     Programmes                                                                                                             Sub Program                                                                                                                                                              Location YR 1 YR 2 YR 3 YR 4 YR 5 Responsible NaN
         156             1                  Improve \nAgricultural \nProduction and \nProductivity a)Infrastructure \nDevelopment Construction of 13 staff houses for \nagricultural extension officers (2 for block \nofficers and 11 for camp officers) Chankumba and Chisamba blocks \n  \nKanakantapa, Ploughman \nB,Chisamba \ncentral,Lwamabwe,Lukoshi,Lombwa,N\nalufwi,Mulungushi \nAgro,Mwapula,Kasosolo and \nMwantaya         3    3    3    4         MOA NaN
         156             1                                                                                                                                                        Rehabilitation of  12 camp houses for \nagricultural extension officers                                                                                        Ploughmans \nB,Chowa,Bombwe,Chikokomene,Lifwa\nmbula/3,Muswishi/4 and Chipembi         3    3    3    3         MOA NaN
         156             1                                                                                                                                                                                    Construction of  7 Veterinary camp \nhouses                                                                                                                                                  All veterinary camps         1    2    2    2         MFL NaN
         156             1                                                                                                                                                                                   Rehabilitation of 5 veterinary camp \nhouses                                                                                                                        2 Lifwambula, 2 Chipembi, 1 \nChisamba central         2    1    1    1         MFL NaN
         156             1                                                                                                                                                                                  Construction of 2 livestock service \ncenters                                                                                                                                 Chisamba central and Muswishi \ncamps         1         1              MFL NaN
         157             2                                                                                                                                                                  Construction of Animal Health \nInfrastructure( 16 Dip tanks)                                                                                         3 Chisamba Central, 3 chisamba \nwest,  4 lifwambula, 3 muswishi,3 \nchipembi         4    4    4    4         MFL NaN
         157             2                                                                                                                                                                                  Construction of 1 livestock breeding \ncenter                                                                                                                                                         Muswishi camp              1                   MFL NaN

In [59]:
import camelot
import pandas as pd

tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="156-249",
    flavor="lattice"
)

all_tables = []

for i, table in enumerate(tables):
    df = table.df.copy()
    df.insert(0, "Source_Page", table.page)
    df.insert(1, "Table_Number", i + 1)
    all_tables.append(df)

raw_idp = pd.concat(all_tables, ignore_index=True)

raw_idp.to_csv(
    "Chisamba_IDP_raw_extracted.csv",
    index=False
)

print("Tables extracted:", len(tables))
print("Raw rows:", len(raw_idp))
print("Raw columns:", len(raw_idp.columns))
print("Saved successfully.")

Tables extracted: 94
Raw rows: 747
Raw columns: 13
Saved successfully.

In [60]:
import camelot
import pandas as pd

tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="143-183",
    flavor="lattice"
)

all_tables = []

for i, table in enumerate(tables):
    df = table.df.copy()
    df.insert(0, "Source_Page", table.page)
    df.insert(1, "Table_Number", i + 1)
    all_tables.append(df)

raw_idp_development = pd.concat(all_tables, ignore_index=True)

raw_idp_development.to_csv(
    "Chisamba_IDP_Development_Framework_raw.csv",
    index=False
)

print("Tables extracted:", len(tables))
print("Raw rows:", len(raw_idp_development))
print("Raw columns:", len(raw_idp_development.columns))
print("Saved successfully.")

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\camelot\utils.py:1514: UserWarning:   (531.7, 534.7580800000001) does not lie in column range (80.88, 531.45)
  warnings.warn(
C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\camelot\utils.py:1514: UserWarning:   (531.22, 534.3112) does not lie in column range (80.03999999999999, 531.0)
  warnings.warn(
C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\camelot\utils.py:1514: UserWarning:   (531.7, 535.024) does not lie in column range (80.75999999999999, 531.4200000000001)
  warnings.warn(

Tables extracted: 29
Raw rows: 271
Raw columns: 13
Saved successfully.

In [61]:
import camelot
import pandas as pd

tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="202-249",
    flavor="lattice"
)

all_tables = []

for i, table in enumerate(tables):
    df = table.df.copy()
    df.insert(0, "Source_Page", table.page)
    df.insert(1, "Table_Number", i + 1)
    all_tables.append(df)

raw_idp_capital = pd.concat(all_tables, ignore_index=True)

raw_idp_capital.to_csv(
    "Chisamba_IDP_Capital_Investment_raw.csv",
    index=False
)

print("Tables extracted:", len(tables))
print("Raw rows:", len(raw_idp_capital))
print("Raw columns:", len(raw_idp_capital.columns))
print("Saved successfully.")

Tables extracted: 47
Raw rows: 284
Raw columns: 13
Saved successfully.

In [62]:
import camelot
import pandas as pd

tables = camelot.read_pdf(
    "IDP_2024_2034.pdf",
    pages="135-137",
    flavor="lattice"
)

all_tables = []

for i, table in enumerate(tables):
    df = table.df.copy()
    df.insert(0, "Source_Page", table.page)
    df.insert(1, "Table_Number", i + 1)
    all_tables.append(df)

raw_idp_problems = pd.concat(all_tables, ignore_index=True)

raw_idp_problems.to_csv(
    "Chisamba_IDP_Problems_Issues_raw.csv",
    index=False
)

print("Tables extracted:", len(tables))
print("Raw rows:", len(raw_idp_problems))
print("Raw columns:", len(raw_idp_problems.columns))
print("Saved successfully.")

Tables extracted: 3
Raw rows: 12
Raw columns: 5
Saved successfully.

In [63]:
import requests
url = "https://www.chisambacouncil.gov.zm/wp-content/uploads/2025/12/MINUTES-OF-STAKEHOLDERS-FOR-COMMUNITY-PROJECT-FOR-BUDGET-INPUT-FOR-THE-YEAR-2025.pdf"
response = requests.get(url, verify=False)
print(response.size)
print(len(response.content))

C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.chisambacouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

AttributeError: 'Response' object has no attribute 'size'

In [64]:
with open("Chisamba_2025_Stakeholder_Minutes.pdf", "wb") as f:
    f.write(response.content)

print("PDF saved")

PDF saved

In [66]:
from pdf2image import convert_from_path
pages = convert_from_path(
"Chisamba_2025_Stakeholder_Minutes.pdf",dpi=300,
poppler_path=r"C:\Program Files\poppler-26.07.0\Library\bin"
)
print("pages:", len(pages))

pages: 11

In [68]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

In [69]:
ocr_text = []

for i, page in enumerate(pages):
    text = pytesseract.image_to_string(page)
    ocr_text.append(text)
    
    print(f"Page {i + 1} processed")

Page 1 processed
Page 2 processed
Page 3 processed
Page 4 processed
Page 5 processed
Page 6 processed
Page 7 processed
Page 8 processed
Page 9 processed
Page 10 processed
Page 11 processed

In [70]:
print(ocr_text[0])

REPUBLIC OF ZAMBIA

MINISTRY OF LOCAL GOVERNMENT
AND RURAL DEVELOPMENT

Stakeholder Meeting Minutes

Zambia Devolution Support Program

Page | |

Ics} CamScanner

In [71]:
print(ocr_text[5])

MISWA
MISWA
MISWA
COMMUNITY MEMBER
155

| 1 56 | EDWIN MWIINGA COMMUNITY MEMBER_ | MISWA
157 | BRADLON KANYEMBA COMMUNITY MEMBER _| MISWA
158 | PLANWELL MBOSHA COMMUNITY MEMBER _| MISWA

159

JOSEPH MATOONGA COMMUNITY MEMBER _| MISWA
0 | PROMISE MABENGA COMMUNITY MEMBER __| MISWA

16
COMMUNITY MEMBER |MISWA |
[162 | STEPHEN BWALYA | COMMUNITYMEMBER |MISWA__|
'163 | MAXIMO MALAMA |COMMUNITY MEMBER |MISWA |
'ie4|PAULKATELELE _|COMMUNITYMEMBER |MISWA_|
165 | CONSTEVIOUS MOSHI__|COMMUNITY MEMBER |MISWA
rie6|SACKSONKATELELE |COMMUNITYMEMBER |MISWA |
COMMUNITY MEMBER _| CHIKONKOMENE |
| 168 | AMOS MANEMA COMMUNITY MEMBER | CHIKONKOMENE |
| 169 | COMMUNITY MEMBER

M170 TOMSONNJOVU ___| COMMUNITY MEMBER _| CHIKONKOMENE |
[171 |FUNWELLMWEENE _| COMMUNITY MEMBER
COMMUNITY MEMBER
CHIKONKOMENE
RUEBEN MUYANGA COMMUNITY MEMBER
176 |FRANCISSELENJE | COMMUNITY MEMBER | CHIKONKOMENE |
177
78 COMMUNITY MEMBER
COMMUNITY MEMBER

—

PRAYER

Councillor Chimanda Moonga.

AGENDA

Opening Prayer
Introductions / Roll Call

Opening Remarks
Presentation on Budget Performance update

PO De

In [72]:
ocr_stakeholder_tables = []

for i in range(1, 9):
    text = pytesseract.image_to_string(pages[i])
    ocr_stakeholder_tables.append(text)
    print(f"Page {i + 1} processed")

Page 2 processed
Page 3 processed
Page 4 processed
Page 5 processed
Page 6 processed
Page 7 processed
Page 8 processed
Page 9 processed

In [74]:
raw_table_stakeholder_text = "\n\n".join(ocr_stakeholder_tables)

print(raw_table_stakeholder_text)

CHISAMBA TOWN COUNCIL

MINUTES OF THE ENGAGEMENT OF STAKEHOLDERS ON BUDGET INPUT OF
COMMUNITY PROJECTS FOR 2024-2025 HELD ON 18ST AUGUST AND 23®°

SEPTEMBER, 2024 AT 10:30HOURS.
ATTENDANCE LIST:

CHIMANDA MOONGA COUNCILLOR

2

| 2 |MOSESHAMOONGA __| CWAC CHAIRPERSON
| 3|AUSTENLUBABA __| CWAC CHAIRPERSON _| MWAPULA
eon | ewasentitemabn.. |

ZIKAMUNDENGA CWAC CHAIPERSON MWAPULA
[Ss |HARDSONMELEKI_|CWAC——S*s[CHAMUKA
| 6 | ATRINA MWIINDE fcwacCsd
ESTHER MAILA
[—s|CHIBESALIZZY | CWAC CHAIRPERSON |CHAMUKA _|
| 9 | MAFUWA BARBRAH C
¢
[ai /LUNGUEPHRAIM—«||CWAC | CHAMUKA

MUPENYU SIMBA COUNCILLOR

© plelsbs sla lela
nN o1 | |o |bo

:

SI

:

:

3

=

Q

i

n

tH

Q

a

2:

a

SI

5
S
a
B
Q
ES
es
2
O
a2
kK
:
]

CWAC CHAIPERSON MWANTAYA

sales |
2

Z

=

8

5

ES}

|

3 Q
}

Page | 2


REPUBLIC OF ZAMBIA
MINISTRY OF LOCAL GOVERNMENT
AND HOUSING

iy al 2 3 crp jae
Hee 3 2024 oe
i CHSAMBATOUNGOURCL |
i COUNCIL. SECRETARY !
{| PO. BOX BBOO3N ClticAnap

AC CHAIRPERSON *~

PAUL BANDA CW.
CWAC CHAIRPERSON

[27 |[SIMONCHACHA __|
26 [MIKE MULEYA | WDC CHAIRPERSON | MUSWISHI__
“29 REUBENNONA [Woo | MUSWISHI _

2ZiNe

| 34 | MATILDAH CHIMUKA _| COMMUNITY MEMBER [MUSWISHI —_|
| 35 | JENIPHER CHATOLA COMMUNITY MEMBER | MUSWISHI_|
STENFORD SIAUMPE COMMUNITY MEMBER |MUSWISHI
37 PATSONKUNDA ____| COMMUNITY MEMBER | MUSWISHI___
| 38 | GODFREY MWANDO _| COMMUNITY MEMBER [MUSWISHI |
COMMUNITY MEMBER | MUSWISHI_|
40 [FRED CHALWE | COMMUNITY MEMBER | MUSWISHI__
| 41 | ELIZABETHLUNGU_| COMMUNITY MEMBER [MWANTAYA
| 42|LOVELIKOMBA _—_| COMMUNITY MEMBER [MWANTAYA _|
43 SHULAJESSY | COMMUNITY MEMBER_|MWANTAYA __|
"44 HILDAH CHIPEPO _| COMMUNITY MEMBER __ MWANTAYA

| 45 | MAGGLE CHILANDO COMMUNITY MEMBER | MWANTAYA

COMMUNITY MEMBER
AMAILA COMMUNITY MEMBER
CONSTRIBAH MUKONKA | COMMUNITY MEMBER MWANTAYA
MUNI

|
:
:

Z
:

| 49 | PEPHIASBWEMBYA _| COMMUNITY MEMBER
| 50 | MEMORY KUPENGA__| COMMUNITY MEMBER
51 | CHRISTINANG’ANDU |COMMUNITY MEMBER [MUTENGA |
[52 EUNICALUPIYA ‘| COMMUNITY MEMBER
ee eee
53 | HANKAKAKI COMMUNITY MEMBER _| MUTENGA

| 54 | EDNA NAKALUMBA COMMUNITY MEMBER
| s5|BENJAMINMALOOT _| COMMUNITY MEMBER
"56 | STANLEY MACHAYA _| COMMUNITY MEMBER
MON G COMMUNITY MEMBER

TY MEMBER
Pome [wren

MUNITY MEMBER GA
PHANWELL MWEEMBA | COMMUNITY MEMBER |MUTENGA
MUNITY MEMBER |MUTENGA |
TYMEMBER |MUTENGA |
TYMEMBER |MUTENGA

MUNI
MUNI

-¢5 | DOMINIC MWEEMBA _| COMMUNITY MEMBER [MUTENGA _—i|
MUNI

=
a
i

:

:

TY MEMBER

MUTENGA

Page | 3


MUNI
COMMUNITY MEMBER
MUNITY MEMBER

COMMUNITY MEMBER
COMMUNITY MEMBER

ANKAMBA GIFT
IREEN CHITOMPE COMMUNITY MEMBER
BRIDGET DAKA
| 80 | ALICA CHITOMPE
MERVIS TITOLE

COMMUNITY MEMBER

COMMUNITY MEMBER

[84 |
| 85 |
| 86 | CHIBI
AH CHANGNLN
VENESS DIMUNA
IRL DIMA COMMUNITY MEMBER

AMWASDA

al
co

i /2/2
(
ir
al
re)

:
g
5
S

te
Q

e
ef
O
:
g
eS
;
a
:
:
F
5
:
He)

ro)

| 92 | IREEN DAKA COMMUNITY MEMBER | CHISAMBA
| 93 | COMMUNITY MEMBER | CHISAMBA

COMMUNITY MEMBER _| CHISAMBA
COMMUNITY MEMBER | CHISAMBA

| 96 | LIZZLE BWALYA COMMUNITY MEMBER | CHISAMBA

IRS |=
i
ae
re

<

5

MERCY PATA COMMUNITY MEMBER | CHISAMBA
COMMUNITY MEMBER | CHISAMBA

COMMUNITY MEMBER _| CHISAMBA

106 | SHARON KOZOKA COMMUNITY MEMBER | CHISAMBA
MONANG'OMBE

MONANG'OMBE

Page | 4


LONTIA MOONGA

GRADUATE

132 | DELPHISTER MUSENGO_| COMMUNITY MEMBER

Q
Oo
s
|
S
Ss
Ey
w
5
4|4
Be
a\a
ohio)
5 |s
mm | ti

[134 | EVANS PHEN COMMUNITY MEMBER

135 | STANLEY HIMONZOWA_| COMMUNITY MEMBER

WILLIAM SIPIMTOL COMMUNITY MEMBER

MWENYA JOSEPHINE
IFFORD NGAMBI COM TY MEMBER
TY MEMBER _ | MISWA

|
<

==

coal (alll Lumet (nee
G |G) |G |G
© 1O|N |o

HADREK MAKONISO COM

AE

MMANUEL MOONGA COM TY MEMBER _| MISWA

140 | E
DANFORD CHOONGO
OWEN CHILEMBO

COMMUNITY MEMBER
COMMUNITY MEMBER
COMMUNITY MEMBER
COMMUNITY MEMBER

Page | 5


MISWA
MISWA
MISWA
COMMUNITY MEMBER
155

| 1 56 | EDWIN MWIINGA COMMUNITY MEMBER_ | MISWA
157 | BRADLON KANYEMBA COMMUNITY MEMBER _| MISWA
158 | PLANWELL MBOSHA COMMUNITY MEMBER _| MISWA

159

JOSEPH MATOONGA COMMUNITY MEMBER _| MISWA
0 | PROMISE MABENGA COMMUNITY MEMBER __| MISWA

16
COMMUNITY MEMBER |MISWA |
[162 | STEPHEN BWALYA | COMMUNITYMEMBER |MISWA__|
'163 | MAXIMO MALAMA |COMMUNITY MEMBER |MISWA |
'ie4|PAULKATELELE _|COMMUNITYMEMBER |MISWA_|
165 | CONSTEVIOUS MOSHI__|COMMUNITY MEMBER |MISWA
rie6|SACKSONKATELELE |COMMUNITYMEMBER |MISWA |
COMMUNITY MEMBER _| CHIKONKOMENE |
| 168 | AMOS MANEMA COMMUNITY MEMBER | CHIKONKOMENE |
| 169 | COMMUNITY MEMBER

M170 TOMSONNJOVU ___| COMMUNITY MEMBER _| CHIKONKOMENE |
[171 |FUNWELLMWEENE _| COMMUNITY MEMBER
COMMUNITY MEMBER
CHIKONKOMENE
RUEBEN MUYANGA COMMUNITY MEMBER
176 |FRANCISSELENJE | COMMUNITY MEMBER | CHIKONKOMENE |
177
78 COMMUNITY MEMBER
COMMUNITY MEMBER

—

PRAYER

Councillor Chimanda Moonga.

AGENDA

Opening Prayer
Introductions / Roll Call

Opening Remarks
Presentation on Budget Performance update

PO De



5, Submission of 2025 Budget Inputs
6. Plenary
7. Closing Remarks
After due consideration and on a prop
by Mr. Buxstone Moomba the agenda was adopted.

osal by Ms. Margaret Lundako and seconded

OPENING REMARKS
welcomed the

the Socio Economic Planner,
ged positive

In opening the budget input meetings,
community members and everyone present to the meeting and encoura

participation in submitting the inputs.

BICP/23/08/24 BUDGET PERFORMANCE UPDATE

mance by program was presented as

The 2024 budget perfor
follows:

%
variance(+/-

7 2024 2024 ACTUAL -
Programme Name BUDGET )
| Programe Ne ag | eiangaa| ——_soan.ai | ___#
[1 | Genet Borsiceett — |" esas | —_aussane | —_—Se
[2 [oes ovemaice ——Fansing | s.senaoo| 490001} ___81
eee [eel mae a
4 | Development 151,477 78,965 48
PR emg ane! a
Protection 3,498,334 a7
[8 | Protection ny Amonlien | s.eie08| —_10i6as8 | _2
8 Hes nd Religion | _Lostaea| _ess.oaa | _s
Ce a cela Dersiopmed of STOO |
[8 Ea eee | —oaagout| —_—ee.ane | __
[2 [Publi ses a Soppow Services | l.ee7050[ 22400 {_27
Resource Mobilisation and
2usneeet gaidee | aatogon| Stesgea| __
[CS |

il aie ie bee

REPUBL Pe
M IC OF ZAN,3i3
INISTRY OF Loca, Gove

AND HOLS) VERN

“WV

MENT

INC Ay
COUNCIL SECREONCUL
A Page | 7

__ PO. BOX gr
‘ praenanen OX 62003 O, CHISA hi
On en ‘MBA 4


aia Hp

REPUBLIC Os Zany
MINISTRY OF ioc Gone
SRY OF LOCAL Gave:
pe pale 2VFRNMENT
, a re,
A hy “7
Eur not.
Copley 2 3 SED 2024 fleas) :
AN Ee ere ay ae ree, absens y
CHISAMBA TOWN mer
Pg COUNCIL SECRETARY”
ecremsetcemae 820030, CHISAMBA

BICP/24/08/24 SUBMISSION OF 2025 BUDGET INPUTS ~~

The following were the community submissions of Budget input

for 2024/2025 projects from the wards,
that the projects should be projects that
The projects were prioritized and submit

01 | Mutenga
School
Monag’ombwe
(Projects
according to | Electrification of a school and teachers houses
10 boreholes of water
03 | Mulungushi
(Projects
where submitted | School
zones)
| Chisamba CBD

Zone Monagobwe
k, 3 teachers house & 14
Mwapula l
3 Teachers houses

1 by 3 classroom bloc
boreholes
Zone Bombwe
1 by 3 classroom block at Nasambila Community
Maternity annex
—
secondary school
1 by 3 classroom block in Makeni
Zone: Kalangwa
Construction of a Health post

the facilitator emphasized
are in line with the IDP.
ted three per ward.

(Projects
where submitted
according to
zones)



Liteta Completion of Nalufwi Prima School
Completion of Tushomeke Community School __|

(Projects where ompletion of Tushomeke Communi

Cc
schools
Chikonkomene
1 by 2 classroom block at Chikonkomene High
School

a Teachers houses

10 | Mwataya 1 by 3 classroom block
Construction of a Matern of a Materni ae

3 Drilling of boreholes (100 meters deep
gue Construction of a Health post and Maternit annex
1 by 3 classroom block

4 Drilling of 100 meters) deep boreholes
12 Sn effiealth post of Health post
Const in all ine 4 zones borehole each in all the 4 zones
See ee ———— by 2 classroom block

BICP/25/08/24 PLENARY
The meeting discussed the following items:

I. Grading of roads
Il. Feedback on the approved CDF projects, Grants and Loans

I. Collection of garbage at Chisamba and Liteta markets
Iv. Payment of levies

CLOSING REMARKS:
onomic Planner thanked the stakeholders for their

In closing the meeting, the Socio Ec
gaging the Council anytime for

active participation and urged them to continue en
better development of the District.

Page | 9

In [75]:
table1_page = pages[6]

table1_text = pytesseract.image_to_string(table1_page)

print(table1_text)

5, Submission of 2025 Budget Inputs
6. Plenary
7. Closing Remarks
After due consideration and on a prop
by Mr. Buxstone Moomba the agenda was adopted.

osal by Ms. Margaret Lundako and seconded

OPENING REMARKS
welcomed the

the Socio Economic Planner,
ged positive

In opening the budget input meetings,
community members and everyone present to the meeting and encoura

participation in submitting the inputs.

BICP/23/08/24 BUDGET PERFORMANCE UPDATE

mance by program was presented as

The 2024 budget perfor
follows:

%
variance(+/-

7 2024 2024 ACTUAL -
Programme Name BUDGET )
| Programe Ne ag | eiangaa| ——_soan.ai | ___#
[1 | Genet Borsiceett — |" esas | —_aussane | —_—Se
[2 [oes ovemaice ——Fansing | s.senaoo| 490001} ___81
eee [eel mae a
4 | Development 151,477 78,965 48
PR emg ane! a
Protection 3,498,334 a7
[8 | Protection ny Amonlien | s.eie08| —_10i6as8 | _2
8 Hes nd Religion | _Lostaea| _ess.oaa | _s
Ce a cela Dersiopmed of STOO |
[8 Ea eee | —oaagout| —_—ee.ane | __
[2 [Publi ses a Soppow Services | l.ee7050[ 22400 {_27
Resource Mobilisation and
2usneeet gaidee | aatogon| Stesgea| __
[CS |

il aie ie bee

REPUBL Pe
M IC OF ZAN,3i3
INISTRY OF Loca, Gove

AND HOLS) VERN

“WV

MENT

INC Ay
COUNCIL SECREONCUL
A Page | 7

__ PO. BOX gr
‘ praenanen OX 62003 O, CHISA hi
On en ‘MBA 4

In [76]:
import pytesseract
from pytesseract import Output
import pandas as pd
admin_data = []

for page_num in range(1, 6):
    data = pytesseract.image_to_data(
        pages[page_num],
        output_type=Output.DATAFRAME
    )
    
    data = data.dropna(subset=["text"])
    data = data[data["text"].str.strip() != ""]
    
    data["page"] = page_num + 1
    
    admin_data.append(data)

admin_data = pd.concat(admin_data, ignore_index=True)

print("Rows:", len(admin_data))

Rows: 801

In [77]:
admin_data.head(30)

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text,page
0,5,1,2,1,1,1,801,820,303,41,91.771889,CHISAMBA,2
1,5,1,2,1,1,2,1120,817,176,40,96.224960,TOWN,2
2,5,1,2,1,1,3,1314,813,266,41,96.260727,COUNCIL,2
3,5,1,4,1,1,1,288,982,216,35,96.138077,MINUTES,2
4,5,1,4,1,1,2,520,980,67,33,95.211098,OF,2
5,5,1,4,1,1,3,602,980,95,32,95.211098,THE,2
6,5,1,4,1,1,4,712,975,355,37,96.178459,ENGAGEMENT,2
7,5,1,4,1,1,5,1082,974,67,34,96.837029,OF,2
8,5,1,4,1,1,6,1163,968,384,39,96.455559,STAKEHOLDERS,2
9,5,1,4,1,1,7,1563,965,75,34,96.812431,ON,2
10,5,1,4,1,1,8,1651,961,204,36,96.215141,BUDGET,2
11,5,1,4,1,1,9,1870,957,151,35,96.123199,INPUT,2
12,5,1,4,1,1,10,2036,956,67,34,96.695190,OF,2
13,5,1,4,1,2,1,290,1040,318,37,95.671722,COMMUNITY,2
14,5,1,4,1,2,2,637,1037,244,45,96.406006,PROJECTS,2
15,5,1,4,1,2,3,912,1036,103,33,96.406006,FOR,2
16,5,1,4,1,2,4,1044,1033,214,35,96.731453,2024-2025,2
17,5,1,4,1,2,5,1289,1030,131,35,96.946877,HELD,2
18,5,1,4,1,2,6,1452,1028,73,34,95.549217,ON,2
19,5,1,4,1,2,7,1559,1021,58,39,78.478447,18ST,2
20,5,1,4,1,2,8,1645,1021,192,36,95.500854,AUGUST,2
21,5,1,4,1,2,9,1867,1018,105,34,92.401520,AND,2
22,5,1,4,1,2,10,2005,1011,96,39,20.855934,23®°,2
23,5,1,5,1,1,1,291,1101,301,40,96.079666,"SEPTEMBER,",2
24,5,1,5,1,1,2,610,1098,99,35,96.797470,2024,2
25,5,1,5,1,1,3,722,1098,63,33,93.202164,AT,2
26,5,1,5,1,1,4,801,1095,292,35,91.705299,10:30HOURS.,2
27,5,1,5,1,2,1,291,1191,331,36,96.167297,ATTENDANCE,2
28,5,1,5,1,2,2,636,1190,117,34,94.706543,LIST:,2
29,5,1,6,1,1,1,446,1347,232,32,90.220024,CHIMANDA,2

In [78]:
page2_table = admin_data[
    (admin_data["page"] == 2) &
    (admin_data["top"] >= 1300)
]

page2_table[[
    "left", "top", "width", "height", "conf", "text"
]].head(50)

    left   top  width  height       conf                               text
29   446  1347    232      32  90.220024                           CHIMANDA
30   688  1344    200      33  92.218918                             MOONGA
31   981  1340    271      34  96.892967                         COUNCILLOR
33   313  1381     24      72  43.862511                                  |
34   373  1391     36      56   0.000000                                  2
35   421  1385    536      62   0.000000                     |MOSESHAMOONGA
36   877  1381     90      72  38.781395                                __|
37   980  1399    133      32  89.484818                               CWAC
38  1127  1396    290      34  95.582664                        CHAIRPERSON
39   313  1432     26      77  47.140419                                  |
40   317  1436   1160      69  30.549026                     3|AUSTENLUBABA
41   839  1432    135      77   9.522018                                __|
42   999  1432    110      77  91.959076                               CWAC
43  1134  1432    283      77  77.731941                        CHAIRPERSON
44  1435  1432     59      77  69.507225                                 _|
45  1500  1448    217      34  92.272003                            MWAPULA
46   318  1494   1159     113  29.809677                                eon
47   890  1490     75     128  32.840111                                  |
48   986  1494    459     113   0.000000                   ewasentitemabn..
49  1455  1490     22     128  78.793983                                  |
50   447  1559    339      45  91.476570                       ZIKAMUNDENGA
51   981  1559    132      32  92.226402                               CWAC
52  1127  1556    264      34  92.233521                         CHAIPERSON
53  1495  1548    224      44  84.677956                            MWAPULA
54   314  1586     97      83  15.344193                                [Ss
55   424  1590   1447      75   0.000000  |HARDSONMELEKI_|CWAC——S*s[CHAMUKA
56   313  1660     24      72  75.903442                                  |
57   367  1667     36      55  62.456501                                  6
58   421  1660     18      72  92.067574                                  |
59   446  1680    153      31  90.747688                             ATRINA
60   608  1678    193      32  92.555206                            MWIINDE
61   959  1652    517      62   0.000000                           fcwacCsd
62   446  1737    155      31  93.245667                             ESTHER
63   610  1735    133      32  92.890793                              MAILA
64   316  1763   1553      73   0.000000                   [—s|CHIBESALIZZY
65   865  1759    109      81   3.397430                                  |
66  1000  1759    109      81   0.000000                               CWAC
67  1122  1759    311      81   0.000000                        CHAIRPERSON
68  1459  1759    257      81  44.491886                           |CHAMUKA
69  1756  1759    116      81  49.148529                                 _|
70   312  1831     24      72  79.661293                                  |
71   366  1838     36      57  40.879093                                  9
72   420  1831     24      72  92.724785                                  |
73   445  1851    191      32  91.940826                             MAFUWA
74   645  1848    188      34  92.278412                            BARBRAH
75  1498  1840     28      30  51.164017                                  C
76  1497  1898     27      30  32.986275                                  ¢
77   311  1936     98      78  10.857269                                [ai
78   421  1940   1051      70   1.611557              /LUNGUEPHRAIM—«||CWAC
79  1318  1936    170      78   6.946175                                  |

In [79]:
administrative_dataset = []

for page, page_df in admin_data.groupby("page"):

    # Sort OCR elements from top to bottom
    page_df = page_df.sort_values("top")

    # Group words into rows based on vertical position
    rows = []
    current_row = []
    current_y = None

    for _, item in page_df.iterrows():

        if current_y is None:
            current_y = item["top"]
            current_row = [item]

        elif abs(item["top"] - current_y) <= 30:
            current_row.append(item)

        else:
            rows.append(current_row)
            current_row = [item]
            current_y = item["top"]

    if current_row:
        rows.append(current_row)

    # Convert each OCR row into columns
    for row in rows:

        row = sorted(row, key=lambda x: x["left"])

        no = []
        name = []
        position = []
        ward = []

        for item in row:

            x = item["left"]
            text = str(item["text"]).strip()

            if x < 440:
                no.append(text)

            elif x < 950:
                name.append(text)

            elif x < 1490:
                position.append(text)

            else:
                ward.append(text)

        administrative_dataset.append({
            "No": " ".join(no),
            "Name": " ".join(name),
            "Position": " ".join(position),
            "Ward": " ".join(ward)
        })

In [80]:
admin_df = pd.DataFrame(administrative_dataset)

In [81]:
admin_df.head(20)

,No,Name,Position,Ward
0,,CHISAMBA,TOWN COUNCIL,
1,MINUTES,OF THE ENGAGEMENT,OF STAKEHOLDERS,ON BUDGET INPUT OF
2,COMMUNITY,PROJECTS FOR,2024-2025 HELD ON,18ST AUGUST AND 23®°
3,"SEPTEMBER,",2024 AT 10:30HOURS.,,
4,ATTENDANCE,LIST:,,
5,2,,,
6,,CHIMANDA MOONGA,COUNCILLOR,
7,| 2 |MOSESHAMOONGA,__|,CWAC CHAIRPERSON,
8,| 3|AUSTENLUBABA,__|,CWAC CHAIRPERSON _|,MWAPULA
9,eon,|,ewasentitemabn.. |,
10,,ZIKAMUNDENGA,CWAC CHAIPERSON,MWAPULA
11,[Ss |HARDSONMELEKI_|CWAC——S*s[CHAMUKA,,,
12,| 6 |,ATRINA MWIINDE,fcwacCsd,
13,[—s|CHIBESALIZZY,ESTHER MAILA |,CWAC CHAIRPERSON |CHAMUKA,_|
14,| 9 |,MAFUWA BARBRAH,,C
15,,,,¢
16,[ai /LUNGUEPHRAIM—«||CWAC,,|,CHAMUKA
17,plelsbs lela |bo,,,
18,|o,,,
19,|,,,

In [82]:
admin_df.to_csv(
    "Chisamba_2025_Administrative_Dataset.csv",
    index=False
)

print("Administrative dataset saved.")

Administrative dataset saved.